var Constants = {
  PrayerTimeCalculation: {
    CalculationMethod: {
      Names: ["MWL", "ISNA", "Egypt", "Karachi", "Tehran", "Jafari"],
    },

    AsrJuristic: {
      Names: ["Standard", "Hanafi"],
    },

    MidnightMethods: {
      Names: ["Standard", "Jafari"],
      Standard: "Standard",
      Jafari: "Jafari",
    },

    HighLatMethods: {
      Names: ["NightMiddle", "AngleBased", "OneSeventh", "None"],
      NightMiddle: "NightMiddle",
      AngleBased: "AngleBased",
      OneSeventh: "OneSeventh",
      None: "None",
    },
    timeFormats: {
      Format_24h: "24h",
      Format_12h: "12h",
      Format_12hNS: "12hNS",
      Format_Float: "Float",
    },
  },
  daysNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  MonthNameEnglish: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
};

var countries = {
  AFGHANISTAN: {
    citiesNames: ["Kabul", "Kandahar", "Mazar_i_sharif"],
    Kabul: {},
    Kandahar: {},
    Mazar_i_sharif: {},
  },
  ALBANIA: {
    citiesNames: ["Tirana"],
    Tirana: {},
  },
  ALGERIA: {
    citiesNames: [
      "Algiers",
      "Annaba",
      "Bechar",
      "Beni_Isguen",
      "Biskra",
      "Constantine",
      "Djanet",
      "Ghardaia",
      "Hassi_Messaoud",
      "In_Amenas",
      "Oran",
      "Tamanrasset",
      "Tilimsen",
    ],
    Algiers: {},
    Annaba: {},
    Bechar: {},
    Beni_Isguen: {},
    Biskra: {},
    Constantine: {},
    Djanet: {},
    Ghardaia: {},
    Hassi_Messaoud: {},
    In_Amenas: {},
    Oran: {},
    Tamanrasset: {},
    Tilimsen: {},
  },
  ANGOLA: {
    citiesNames: ["Huambo", "Luanda"],
    Huambo: {},
    Luanda: {},
  },
  ARGENTINA: {
    citiesNames: [
      "Bahia_Blanca",
      "Catamarca",
      "Comodoro_Riva",
      "Cordoba",
      "Corrientes",
      "Iguazu",
      "Jujuy",
      "La_Rioja",
      "Mar_Del_Plata",
      "Mendoza",
      "Neuquen",
      "Parana",
      "Paso_Libres",
      "Posadas",
      "Rio_Gallegos",
      "Rosario",
      "Salta",
      "San_Juan",
      "San_Luis",
      "San_Rafael",
      "Santa_Fe",
      "Santa_Rosa",
      "Trelew",
      "Tucuman",
      "Viedma",
    ],
    Bahia_Blanca: {},
    Catamarca: {},
    Comodoro_Riva: {},
    Cordoba: {},
    Corrientes: {},
    Iguazu: {},
    Jujuy: {},
    La_Rioja: {},
    Mar_Del_Plata: {},
    Mendoza: {},
    Neuquen: {},
    Parana: {},
    Paso_Libres: {},
    Posadas: {},
    Rio_Gallegos: {},
    Rosario: {},
    Salta: {},
    San_Juan: {},
    San_Luis: {},
    San_Rafael: {},
    Santa_Fe: {},
    Santa_Rosa: {},
    Trelew: {},
    Tucuman: {},
    Viedma: {},
  },
  ARUBA: {
    citiesNames: ["Aruba"],
    Aruba: {},
  },
  AUSTRALIA: {
    citiesNames: [
      "_Alice_Springs",
      "_Meekatharra",
      "Adelaide",
      "Avalon",
      "Cairns",
      "Canberra",
      "Cowra",
      "Cunnamulla",
      "Darwin",
      "Dubbo",
      "Geraldton",
      "Hobart",
      "Launceston",
      "Learmonth",
      "Mackay",
      "Melbourne",
      "Mount_Isa",
      "Newcastle",
      "Perth",
      "Richmond",
      "Sydney",
      "Townsville",
    ],
    _Alice_Springs: {},
    _Meekatharra: {},
    Adelaide: {},
    Avalon: {},
    Cairns: {},
    Canberra: {},
    Cowra: {},
    Cunnamulla: {},
    Darwin: {},
    Dubbo: {},
    Geraldton: {},
    Hobart: {},
    Launceston: {},
    Learmonth: {},
    Mackay: {},
    Melbourne: {},
    Mount_Isa: {},
    Newcastle: {},
    Perth: {},
    Richmond: {},
    Sydney: {},
    Townsville: {},
  },
  AUSTRIA: {
    citiesNames: ["Graz", "Innsbruck", "Klagenfurt", "Linz", "Vienna"],
    Graz: {},
    Innsbruck: {},
    Klagenfurt: {},
    Linz: {},
    Vienna: {},
  },
  AZERBAIJAN: {
    citiesNames: ["Baku"],
    Baku: {},
  },
  BAHAMAS: {
    citiesNames: ["Cat_Cay", "Freeport", "Nassau", "Rock_Sound", "West_End"],
    Cat_Cay: {},
    Freeport: {},
    Nassau: {},
    Rock_Sound: {},
    West_End: {},
  },
  BAHRAIN: {
    citiesNames: ["Hawar", "Manamah"],
    Hawar: {},
    Manamah: {},
  },
  BANGLADESH: {
    citiesNames: ["Chittagong", "Dhaka"],
    Chittagong: {},
    Dhaka: {},
  },
  BARBADOS: {
    citiesNames: ["Bridgetown"],
    Bridgetown: {},
  },
  BELARUS: {
    citiesNames: ["Gomel", "Hrodna", "Magilev", "Minsk", "Vicebsk"],
    Gomel: {},
    Hrodna: {},
    Magilev: {},
    Minsk: {},
    Vicebsk: {},
  },
  BELGIUM: {
    citiesNames: [
      "Aalst",
      "Antwerp",
      "Bruges",
      "Brussels",
      "Charleroi",
      "Genk",
      "Gent",
      "Hasselt",
      "Kortrijk",
      "La_Louviere",
      "Leuven",
      "Liege",
      "Mechelen",
      "Mons",
      "Namur",
      "Oostende",
      "Roeselare",
      "Saint_Nicolas",
      "Seraing",
      "Tournai",
    ],
    Aalst: {},
    Antwerp: {},
    Bruges: {},
    Brussels: {},
    Charleroi: {},
    Genk: {},
    Gent: {},
    Hasselt: {},
    Kortrijk: {},
    La_Louviere: {},
    Leuven: {},
    Liege: {},
    Mechelen: {},
    Mons: {},
    Namur: {},
    Oostende: {},
    Roeselare: {},
    Saint_Nicolas: {},
    Seraing: {},
    Tournai: {},
  },
  BENIN: {
    citiesNames: ["Cotonou", "Porto_Novo"],
    Cotonou: {},
    Porto_Novo: {},
  },
  BERMUDA: {
    citiesNames: ["Hamilton"],
    Hamilton: {},
  },
  BOLIVIA: {
    citiesNames: ["Cochabamba", "La_Paz", "Santa_Cruz", "Trinidad"],
    Cochabamba: {},
    La_Paz: {},
    Santa_Cruz: {},
    Trinidad: {},
  },
  BOSNIA: {
    citiesNames: ["Sarajevo"],
    Sarajevo: {},
  },
  BOTSWANA: {
    citiesNames: ["Francistown"],
    Francistown: {},
  },
  BRAZIL: {
    citiesNames: [
      "Aracatuba",
      "Belem",
      "Belo_Horizonte",
      "Boa_Vista",
      "Brasilia",
      "Campo_Grande",
      "Crisciuma",
      "Cruzeiro_Do_Sul",
      "Cuiaba",
      "Curitiba",
      "Florianopolis",
      "Fortaleza",
      "Goiania",
      "Iguassu_Falls",
      "Ipatinga",
      "Londrina",
      "Macapa",
      "Manaus",
      "Montes_Claros",
      "Natal",
      "Parnaiba",
      "Pelotas",
      "Ponta_Pora",
      "Porto_Alegre",
      "Porto_Velho",
      "Recife",
      "Rio_Branco",
      "Rio_De_Janeiro",
      "Salvador",
      "Santa_Maria",
      "Santarem",
      "Sao_Jose_D_Campos",
      "Sao_Luiz",
      "Sao_Paulo",
      "Tabatinga",
      "Teresina",
      "Tucurui",
    ],
    Aracatuba: {},
    Belem: {},
    Belo_Horizonte: {},
    Boa_Vista: {},
    Brasilia: {},
    Campo_Grande: {},
    Crisciuma: {},
    Cruzeiro_Do_Sul: {},
    Cuiaba: {},
    Curitiba: {},
    Florianopolis: {},
    Fortaleza: {},
    Goiania: {},
    Iguassu_Falls: {},
    Ipatinga: {},
    Londrina: {},
    Macapa: {},
    Manaus: {},
    Montes_Claros: {},
    Natal: {},
    Parnaiba: {},
    Pelotas: {},
    Ponta_Pora: {},
    Porto_Alegre: {},
    Porto_Velho: {},
    Recife: {},
    Rio_Branco: {},
    Rio_De_Janeiro: {},
    Salvador: {},
    Santa_Maria: {},
    Santarem: {},
    Sao_Jose_D_Campos: {},
    Sao_Luiz: {},
    Sao_Paulo: {},
    Tabatinga: {},
    Teresina: {},
    Tucurui: {},
  },
  BULGARIA: {
    citiesNames: ["Bourgas", "Sofia", "Varna"],
    Bourgas: {},
    Sofia: {},
    Varna: {},
  },
  BURKINA: {
    citiesNames: ["FASO_Bobo_Dioulasso", "FASO_Ouagadougou"],
    FASO_Bobo_Dioulasso: {},
    FASO_Ouagadougou: {},
  },
  BURUNDI: {
    citiesNames: ["Bujumbura"],
    Bujumbura: {},
  },
  Brunei: {
    citiesNames: ["Bandar_Seri_Begawan"],
    Bandar_Seri_Begawan: {},
  },
  CAMBODIA: {
    citiesNames: ["Phnom_Penh", "Siem_Reap"],
    Phnom_Penh: {},
    Siem_Reap: {},
  },
  CAMEROON: {
    citiesNames: ["Douala", "Garoua", "Maroua", "Ngaoundere", "Yaounde"],
    Douala: {},
    Garoua: {},
    Maroua: {},
    Ngaoundere: {},
    Yaounde: {},
  },
  CANADA: {
    citiesNames: [
      "Abbotsford",
      "Baie_Comeau",
      "Brandon",
      "Calgary",
      "Campbell_River",
      "Castlegar",
      "Charlo",
      "Charlottetown",
      "Chatham",
      "Churchill",
      "Cold_Lake",
      "Comox",
      "Cranbrook",
      "Dauphin",
      "Deer_Lake",
      "Dryden",
      "Earlton",
      "Edmonton",
      "Flin_Flon",
      "Fort_Mcmurray",
      "Fort_Nelson",
      "Fort_Simpson",
      "Fort_Smith",
      "Fort_St_John",
      "Fredericton",
      "Frobisher_Bay",
      "Gagnon",
      "Gander",
      "Gatineau",
      "Goose_Bay",
      "Gore_Bay",
      "Grande_Prairie",
      "Halifax",
      "Hamilton",
      "Hay_River",
      "High_Level",
      "Inuvik",
      "Kamloops",
      "Kelowna",
      "Kenora",
      "Kingston",
      "Kuujjuaq",
      "La_Grande",
      "Lac_La_Ronge",
      "Lethbridge",
      "Lloydminster",
      "London",
      "Matane",
      "Medicine_Hat",
      "Moncton",
      "Mont_Joli",
      "Montreal",
      "Muskoka",
      "Nanaimo",
      "North_Bay",
      "Ottawa",
      "Penticton",
      "Port_Hardy",
      "Prince_Albert",
      "Prince_George",
      "Prince_Rupert",
      "Quesnel",
      "Regina",
      "Roberval",
      "Rouyn",
      "Saguenay",
      "Saint_John",
      "Sandspit",
      "Sarnia",
      "Saskatoon",
      "Sept_iles",
      "Sherbrooke",
      "Smithers",
      "St_Johns",
      "Stephenville",
      "Sudbury",
      "Sydney",
      "Terrace",
      "The_Pas",
      "Thunder_Bay",
      "Timmins",
      "Toronto",
      "Trenton",
      "Victoria",
      "Wabush",
      "Watson_Lake",
      "Whitehorse",
      "Williams_Lake",
      "Windsor",
      "Winnipeg",
      "Yarmouth",
      "Yellowknife",
      "Yorkton",
    ],
    Abbotsford: {},
    Baie_Comeau: {},
    Brandon: {},
    Calgary: {},
    Campbell_River: {},
    Castlegar: {},
    Charlo: {},
    Charlottetown: {},
    Chatham: {},
    Churchill: {},
    Cold_Lake: {},
    Comox: {},
    Cranbrook: {},
    Dauphin: {},
    Deer_Lake: {},
    Dryden: {},
    Earlton: {},
    Edmonton: {},
    Flin_Flon: {},
    Fort_Mcmurray: {},
    Fort_Nelson: {},
    Fort_Simpson: {},
    Fort_Smith: {},
    Fort_St_John: {},
    Fredericton: {},
    Frobisher_Bay: {},
    Gagnon: {},
    Gander: {},
    Gatineau: {},
    Goose_Bay: {},
    Gore_Bay: {},
    Grande_Prairie: {},
    Halifax: {},
    Hamilton: {},
    Hay_River: {},
    High_Level: {},
    Inuvik: {},
    Kamloops: {},
    Kelowna: {},
    Kenora: {},
    Kingston: {},
    Kuujjuaq: {},
    La_Grande: {},
    Lac_La_Ronge: {},
    Lethbridge: {},
    Lloydminster: {},
    London: {},
    Matane: {},
    Medicine_Hat: {},
    Moncton: {},
    Mont_Joli: {},
    Montreal: {},
    Muskoka: {},
    Nanaimo: {},
    North_Bay: {},
    Ottawa: {},
    Penticton: {},
    Port_Hardy: {},
    Prince_Albert: {},
    Prince_George: {},
    Prince_Rupert: {},
    Quesnel: {},
    Regina: {},
    Roberval: {},
    Rouyn: {},
    Saguenay: {},
    Saint_John: {},
    Sandspit: {},
    Sarnia: {},
    Saskatoon: {},
    Sept_iles: {},
    Sherbrooke: {},
    Smithers: {},
    St_Johns: {},
    Stephenville: {},
    Sudbury: {},
    Sydney: {},
    Terrace: {},
    The_Pas: {},
    Thunder_Bay: {},
    Timmins: {},
    Toronto: {},
    Trenton: {},
    Victoria: {},
    Wabush: {},
    Watson_Lake: {},
    Whitehorse: {},
    Williams_Lake: {},
    Windsor: {},
    Winnipeg: {},
    Yarmouth: {},
    Yellowknife: {},
    Yorkton: {},
  },
  CAPE: {
    citiesNames: ["VERDE_Sal"],
    VERDE_Sal: {},
  },
  CENTRAL: {
    citiesNames: ["AFERICA_Bangui"],
    AFERICA_Bangui: {},
  },
  CHAD: {
    citiesNames: ["N_djamena"],
    N_djamena: {},
  },
  CHILE: {
    citiesNames: [
      "Antofagasta",
      "Arica",
      "Balmaceda",
      "Calama",
      "Concepcion",
      "Easter_Island",
      "Iquique",
      "Puerto_Montt",
      "Punta_Arenas",
      "Santiago",
    ],
    Antofagasta: {},
    Arica: {},
    Balmaceda: {},
    Calama: {},
    Concepcion: {},
    Easter_Island: {},
    Iquique: {},
    Puerto_Montt: {},
    Punta_Arenas: {},
    Santiago: {},
  },
  CHINA: {
    citiesNames: [
      "Baoshan",
      "Beijing",
      "Guangzhou",
      "Hangzhou",
      "Harbin",
      "Kunming",
      "Lanzhou",
      "Nanning",
      "Shanghai",
      "Shenyang",
      "Taiyuan",
      "Tianjin",
    ],
    Baoshan: {},
    Beijing: {},
    Guangzhou: {},
    Hangzhou: {},
    Harbin: {},
    Kunming: {},
    Lanzhou: {},
    Nanning: {},
    Shanghai: {},
    Shenyang: {},
    Taiyuan: {},
    Tianjin: {},
  },
  COLOMBIA: {
    citiesNames: [
      "Bogota",
      "Bucaramanga",
      "Cali",
      "Cartagena",
      "Medellin",
      "Pereira",
    ],
    Bogota: {},
    Bucaramanga: {},
    Cali: {},
    Cartagena: {},
    Medellin: {},
    Pereira: {},
  },
  COMOROS: {
    citiesNames: ["Moroni"],
    Moroni: {},
  },
  CONGO: {
    citiesNames: ["Brazzaville", "Pointe_Noire"],
    Brazzaville: {},
    Pointe_Noire: {},
  },
  CONNECTICUT: {
    citiesNames: ["Oxford"],
    Oxford: {},
  },
  CORSICA: {
    citiesNames: ["_FRA_Bastia"],
    _FRA_Bastia: {},
  },
  COSTA: {
    citiesNames: ["RICA_Liberia", "RICA_San_Jose"],
    RICA_Liberia: {},
    RICA_San_Jose: {},
  },
  COTE: {
    citiesNames: ["Divoire_Yamoussoukro"],
    Divoire_Yamoussoukro: {},
  },
  CUBA: {
    citiesNames: [
      "Camaguey",
      "Guantanamo",
      "Havana",
      "Holguin",
      "Nueva_Gerona",
      "Santiago",
      "Varadero",
    ],
    Camaguey: {},
    Guantanamo: {},
    Havana: {},
    Holguin: {},
    Nueva_Gerona: {},
    Santiago: {},
    Varadero: {},
  },
  CYPRUS: {
    citiesNames: ["Ercan", "Larnaca", "Paphos"],
    Ercan: {},
    Larnaca: {},
    Paphos: {},
  },
  CZECH: {
    citiesNames: [
      "Budweis",
      "Liberec",
      "Olomouc",
      "Ostrava",
      "Plzen",
      "Prague",
    ],
    Budweis: {},
    Liberec: {},
    Olomouc: {},
    Ostrava: {},
    Plzen: {},
    Prague: {},
  },
  Cocos: {
    citiesNames: ["Islands"],
    Islands: {},
  },
  DENMARK: {
    citiesNames: [
      "Aalborg",
      "Arhus",
      "Copenhagen",
      "Horsens",
      "Kolding",
      "Odense",
      "Randers",
      "Roskilde",
      "Vejle",
    ],
    Aalborg: {},
    Arhus: {},
    Copenhagen: {},
    Horsens: {},
    Kolding: {},
    Odense: {},
    Randers: {},
    Roskilde: {},
    Vejle: {},
  },
  DJIBOUTI: {
    citiesNames: ["Djibouti"],
    Djibouti: {},
  },
  ECUADOR: {
    citiesNames: ["Esmeraldas", "Guayaquil", "Manta", "Quito"],
    Esmeraldas: {},
    Guayaquil: {},
    Manta: {},
    Quito: {},
  },
  EGYPT: {
    citiesNames: [
      "Abu_Simbel",
      "Alexandria",
      "Arish",
      "Asut",
      "Aswan",
      "Banha",
      "Bani_Sweaf",
      "Cairo",
      "Damanhur",
      "Dikirnis",
      "Domyat",
      "Faiyum",
      "Idfu",
      "Ismailiya",
      "Kafr_Al_Dawwar",
      "Kafr_Ash_Shaikh",
      "Luxor",
      "Mahla_Kubra",
      "Mallawi",
      "Mansura",
      "Marsa_Matroh",
      "Minya",
      "Port_Said",
      "Qena",
      "Sharm_El_Shaikh",
      "Shbean_Al_Koam",
      "Sohag",
      "Swais",
      "Talkha",
      "Tanta",
      "Toshka",
      "Zagazig",
    ],
    Abu_Simbel: {},
    Alexandria: {},
    Arish: {},
    Asut: {},
    Aswan: {},
    Banha: {},
    Bani_Sweaf: {},
    Cairo: {},
    Damanhur: {},
    Dikirnis: {},
    Domyat: {},
    Faiyum: {},
    Idfu: {},
    Ismailiya: {},
    Kafr_Al_Dawwar: {},
    Kafr_Ash_Shaikh: {},
    Luxor: {},
    Mahla_Kubra: {},
    Mallawi: {},
    Mansura: {},
    Marsa_Matroh: {},
    Minya: {},
    Port_Said: {},
    Qena: {},
    Sharm_El_Shaikh: {},
    Shbean_Al_Koam: {},
    Sohag: {},
    Swais: {},
    Talkha: {},
    Tanta: {},
    Toshka: {},
    Zagazig: {},
  },
  EQUATORIAL: {
    citiesNames: ["GUINEA_Bata"],
    GUINEA_Bata: {},
  },
  ERITREA: {
    citiesNames: ["Asmara"],
    Asmara: {},
  },
  ESTONIA: {
    citiesNames: ["Kohtla_Jarve", "Narva", "Parnu", "Tallinn", "Tartu"],
    Kohtla_Jarve: {},
    Narva: {},
    Parnu: {},
    Tallinn: {},
    Tartu: {},
  },
  ETHIOPIA: {
    citiesNames: ["Addis_Ababa", "Asmara", "Dire_Dawa"],
    Addis_Ababa: {},
    Asmara: {},
    Dire_Dawa: {},
  },
  FINLAND: {
    citiesNames: [
      "Hameenlinna",
      "Helsinki",
      "Joensuu",
      "Jyvaskyla",
      "Kajaani",
      "Kokkola",
      "Kotka",
      "Kuopio",
      "Lahti",
      "Lappeenranta",
      "Mariehamn",
      "Mikkeli",
      "Oulu",
      "Pori",
      "Porvoo",
      "Rovaniemi",
      "Seinajoki",
      "Tampere",
      "Turku",
      "Vaasa",
      "Vantaa",
    ],
    Hameenlinna: {},
    Helsinki: {},
    Joensuu: {},
    Jyvaskyla: {},
    Kajaani: {},
    Kokkola: {},
    Kotka: {},
    Kuopio: {},
    Lahti: {},
    Lappeenranta: {},
    Mariehamn: {},
    Mikkeli: {},
    Oulu: {},
    Pori: {},
    Porvoo: {},
    Rovaniemi: {},
    Seinajoki: {},
    Tampere: {},
    Turku: {},
    Vaasa: {},
    Vantaa: {},
  },
  FRANCE: {
    citiesNames: [
      "Angers",
      "Bordeaux",
      "Brest",
      "Dijon",
      "Grenoble",
      "Le_Havre",
      "Le_Mans",
      "Lille",
      "Lyon",
      "Marseille",
      "Montpellier",
      "Nantes",
      "Nice",
      "Paris",
      "Reims_",
      "Rennes_",
      "Saint_Etienne",
      "Strasbourg",
      "Toulon",
      "Toulouse",
    ],
    Angers: {},
    Bordeaux: {},
    Brest: {},
    Dijon: {},
    Grenoble: {},
    Le_Havre: {},
    Le_Mans: {},
    Lille: {},
    Lyon: {},
    Marseille: {},
    Montpellier: {},
    Nantes: {},
    Nice: {},
    Paris: {},
    Reims_: {},
    Rennes_: {},
    Saint_Etienne: {},
    Strasbourg: {},
    Toulon: {},
    Toulouse: {},
  },
  GABON: {
    citiesNames: ["Franceville", "Libreville"],
    Franceville: {},
    Libreville: {},
  },
  GAMBIA: {
    citiesNames: ["Banjul"],
    Banjul: {},
  },
  GERMANY: {
    citiesNames: [
      "Aachen",
      "Berlin",
      "Bielefeld",
      "Bochum",
      "Bonn",
      "Bremen",
      "Cologne",
      "Dortmund",
      "Dresden",
      "Duesseldorf",
      "Duisburg",
      "Essen",
      "Frankfurt",
      "Hamburg",
      "Hannover",
      "Leipzig",
      "Mannheim",
      "Munich",
      "Nuernberg",
      "Stuttgart",
      "Wuppertal",
    ],
    Aachen: {},
    Berlin: {},
    Bielefeld: {},
    Bochum: {},
    Bonn: {},
    Bremen: {},
    Cologne: {},
    Dortmund: {},
    Dresden: {},
    Duesseldorf: {},
    Duisburg: {},
    Essen: {},
    Frankfurt: {},
    Hamburg: {},
    Hannover: {},
    Leipzig: {},
    Mannheim: {},
    Munich: {},
    Nuernberg: {},
    Stuttgart: {},
    Wuppertal: {},
  },
  GHANA: {
    citiesNames: ["Accra", "Kumasi"],
    Accra: {},
    Kumasi: {},
  },
  GREECE: {
    citiesNames: [
      "Athens",
      "Chania",
      "Heraklion",
      "Ioannina",
      "Kalamata",
      "Kavalla",
      "Kefalonia",
      "Kos",
      "Larissa",
      "Lemnos",
      "Preveza",
      "Rhodes",
      "Samos",
      "Thessaloniki",
    ],
    Athens: {},
    Chania: {},
    Heraklion: {},
    Ioannina: {},
    Kalamata: {},
    Kavalla: {},
    Kefalonia: {},
    Kos: {},
    Larissa: {},
    Lemnos: {},
    Preveza: {},
    Rhodes: {},
    Samos: {},
    Thessaloniki: {},
  },
  GREENLAND: {
    citiesNames: ["Sondre_Stromfjord"],
    Sondre_Stromfjord: {},
  },
  GUAM: {
    citiesNames: ["Guam"],
    Guam: {},
  },
  GUATEMALA: {
    citiesNames: ["Flores", "Guatemala"],
    Flores: {},
    Guatemala: {},
  },
  GUINEA: {
    citiesNames: ["BISSAU_Bissau", "Conakry"],
    BISSAU_Bissau: {},
    Conakry: {},
  },
  GUYANA: {
    citiesNames: ["Georgetown", "Kaieteur"],
    Georgetown: {},
    Kaieteur: {},
  },
  HAITI: {
    citiesNames: ["Port_Au_Prince"],
    Port_Au_Prince: {},
  },
  HONDURAS: {
    citiesNames: ["La_Ceiba"],
    La_Ceiba: {},
  },
  HONG: {
    citiesNames: ["KONG_Hong_Kong"],
    KONG_Hong_Kong: {},
  },
  HUNGARY: {
    citiesNames: ["Budapest"],
    Budapest: {},
  },
  ICELAND: {
    citiesNames: ["Keflavik"],
    Keflavik: {},
  },
  INDIA: {
    citiesNames: [
      "Ahmedabad",
      "Allahabad",
      "Amritsar",
      "Bangalore",
      "Bhuj",
      "Bombay",
      "Calcutta",
      "Delhi",
      "Gauhati",
      "Hyderabad",
      "Imphal",
      "Lucknow",
      "Madras",
      "Mangalore",
      "Nagpur",
      "Trivandrum",
      "Vadodara",
    ],
    Ahmedabad: {},
    Allahabad: {},
    Amritsar: {},
    Bangalore: {},
    Bhuj: {},
    Bombay: {},
    Calcutta: {},
    Delhi: {},
    Gauhati: {},
    Hyderabad: {},
    Imphal: {},
    Lucknow: {},
    Madras: {},
    Mangalore: {},
    Nagpur: {},
    Trivandrum: {},
    Vadodara: {},
  },
  INDONESIA: {
    citiesNames: [
      "Bandung",
      "Biak",
      "Bogor",
      "Denpasar",
      "Jakarta",
      "Medan",
      "Menado",
      "Surabaya",
    ],
    Bandung: {},
    Biak: {},
    Bogor: {},
    Denpasar: {},
    Jakarta: {},
    Medan: {},
    Menado: {},
    Surabaya: {},
  },
  IRAN: {
    citiesNames: [
      "Abadan",
      "Ahwaz",
      "Bandar_Abbas",
      "Bandar_Lengeh",
      "Bushehr",
      "Esfahan_Ahmadian",
      "Esfahan",
      "Esfahan_Hilal",
      "Kerman",
      "Kermanshah",
      "Mashad",
      "Rasht",
      "Shiraz",
      "Tabriz",
      "Teheran",
      "Yazd",
      "Zahedan",
    ],
    Abadan: {},
    Ahwaz: {},
    Bandar_Abbas: {},
    Bandar_Lengeh: {},
    Bushehr: {},
    Esfahan_Ahmadian: {},
    Esfahan: {},
    Esfahan_Hilal: {},
    Kerman: {},
    Kermanshah: {},
    Mashad: {},
    Rasht: {},
    Shiraz: {},
    Tabriz: {},
    Teheran: {},
    Yazd: {},
    Zahedan: {},
  },
  IRAQ: {
    citiesNames: [
      "Al_Qaim",
      "Amarah",
      "Baghdad",
      "Baiji",
      "Balad",
      "Baqubah",
      "Basrah",
      "Dahuk",
      "Diwaniyeh",
      "Fallujah",
      "Haditha",
      "Hilla",
      "Irbil",
      "Karbala",
      "Kirkuk",
      "Kufah",
      "Kut",
      "Mahmudiyah",
      "Mandali",
      "Moosel",
      "Muqdadiyah",
      "Najaf",
      "Nasiriyah",
      "Ramadi",
      "Rutba",
      "Samarra",
      "Samawah",
      "Sinjar",
      "Sulaymaniyah",
      "Tall_Afar",
      "Tikrit",
    ],
    Al_Qaim: {},
    Amarah: {},
    Baghdad: {},
    Baiji: {},
    Balad: {},
    Baqubah: {},
    Basrah: {},
    Dahuk: {},
    Diwaniyeh: {},
    Fallujah: {},
    Haditha: {},
    Hilla: {},
    Irbil: {},
    Karbala: {},
    Kirkuk: {},
    Kufah: {},
    Kut: {},
    Mahmudiyah: {},
    Mandali: {},
    Moosel: {},
    Muqdadiyah: {},
    Najaf: {},
    Nasiriyah: {},
    Ramadi: {},
    Rutba: {},
    Samarra: {},
    Samawah: {},
    Sinjar: {},
    Sulaymaniyah: {},
    Tall_Afar: {},
    Tikrit: {},
  },
  IRELAND: {
    citiesNames: [
      "Athlone",
      "Bray",
      "Carlow",
      "Clonmel",
      "Cork_",
      "Drogheda",
      "Dublin",
      "Dundalk",
      "Ennis",
      "Galway",
      "Kilkenny",
      "Limerick",
      "Naas",
      "Navan",
      "Newbridge",
      "Sligo",
      "Swords",
      "Tralee",
      "Waterford",
      "Wexford",
    ],
    Athlone: {},
    Bray: {},
    Carlow: {},
    Clonmel: {},
    Cork_: {},
    Drogheda: {},
    Dublin: {},
    Dundalk: {},
    Ennis: {},
    Galway: {},
    Kilkenny: {},
    Limerick: {},
    Naas: {},
    Navan: {},
    Newbridge: {},
    Sligo: {},
    Swords: {},
    Tralee: {},
    Waterford: {},
    Wexford: {},
  },
  ITALY: {
    citiesNames: [
      "Alghero",
      "Ancona",
      "Aviano",
      "Bari",
      "Bergamo",
      "Bologna",
      "Brindisi",
      "Cagliari",
      "Catania",
      "Forli",
      "Grosseto",
      "Lamezia_terme",
      "Milan",
      "Naples",
      "Olbia",
      "Palermo",
      "Pescara",
      "Pisa",
      "Rimini",
      "Rome",
      "Sigonella",
      "Trapani",
      "Trieste",
      "Turin",
      "Venice",
      "Verona",
    ],
    Alghero: {},
    Ancona: {},
    Aviano: {},
    Bari: {},
    Bergamo: {},
    Bologna: {},
    Brindisi: {},
    Cagliari: {},
    Catania: {},
    Forli: {},
    Grosseto: {},
    Lamezia_terme: {},
    Milan: {},
    Naples: {},
    Olbia: {},
    Palermo: {},
    Pescara: {},
    Pisa: {},
    Rimini: {},
    Rome: {},
    Sigonella: {},
    Trapani: {},
    Trieste: {},
    Turin: {},
    Venice: {},
    Verona: {},
  },
  IVORY: {
    citiesNames: ["COAST_Abidjan", "COAST_Bouake"],
    COAST_Abidjan: {},
    COAST_Bouake: {},
  },
  JAMAICA: {
    citiesNames: ["Kingston", "Montego_Bay"],
    Kingston: {},
    Montego_Bay: {},
  },
  JAPAN: {
    citiesNames: [
      "Akita",
      "Atsugi",
      "Fukuoka",
      "Hachinohe",
      "Hakodate",
      "Kagoshima",
      "Komatsu",
      "Kumamoto",
      "Matsuyama",
      "Misawa",
      "Nagasaki",
      "Nagoya",
      "Niigata",
      "Obihiro",
      "Okinawa",
      "Osaka",
      "Sapporo",
      "Sendai",
      "Shimojishima",
      "Tokyo",
      "Ube",
      "Yamagata",
    ],
    Akita: {},
    Atsugi: {},
    Fukuoka: {},
    Hachinohe: {},
    Hakodate: {},
    Kagoshima: {},
    Komatsu: {},
    Kumamoto: {},
    Matsuyama: {},
    Misawa: {},
    Nagasaki: {},
    Nagoya: {},
    Niigata: {},
    Obihiro: {},
    Okinawa: {},
    Osaka: {},
    Sapporo: {},
    Sendai: {},
    Shimojishima: {},
    Tokyo: {},
    Ube: {},
    Yamagata: {},
  },
  JORDAN: {
    citiesNames: [
      "Amman",
      "Ajloun",
      "Aqaba",
      "Azraq",
      "Bayer",
      "Dayr_Abu_Saeed",
      "Gharandal",
      "Hasa",
      "Hmeadeyeh",
      "Irbid",
      "Jafer",
      "Jarash",
      "Karak",
      "Maan",
      "Madaba",
      "Mafraq",
      "Mdawarah",
      "NorthShouneh",
      "Omari",
      "Qatraneh",
      "Qwearah",
      "Rahmah",
      "Rum",
      "Rweashed",
      "Safawi",
      "Safi",
      "Salt",
      "Shoubak",
      "Shoubak_Wadi_Mousa",
      "SouthHusayneyah",
      "SouthShouneh",
      "Tafeleh",
      "Zarqa",
    ],
    Amman: {},
    Ajloun: {},
    Aqaba: {},
    Azraq: {},
    Bayer: {},
    Dayr_Abu_Saeed: {},
    Gharandal: {},
    Hasa: {},
    Hmeadeyeh: {},
    Irbid: {},
    Jafer: {},
    Jarash: {},
    Karak: {},
    Maan: {},
    Madaba: {},
    Mafraq: {},
    Mdawarah: {},
    NorthShouneh: {},
    Omari: {},
    Qatraneh: {},
    Qwearah: {},
    Rahmah: {},
    Rum: {},
    Rweashed: {},
    Safawi: {},
    Safi: {},
    Salt: {},
    Shoubak: {},
    Shoubak_Wadi_Mousa: {},
    SouthHusayneyah: {},
    SouthShouneh: {},
    Tafeleh: {},
    Zarqa: {},
  },
  KAZAKHSTAN: {
    citiesNames: [
      "Almaty",
      "Aqtobe",
      "Astana",
      "Karaganda",
      "Oskemen",
      "Pavlodar",
      "Petropavl",
      "Qostanay",
      "Semey",
      "Shymkent",
      "Taraz",
      "Temirtau",
    ],
    Almaty: {},
    Aqtobe: {},
    Astana: {},
    Karaganda: {},
    Oskemen: {},
    Pavlodar: {},
    Petropavl: {},
    Qostanay: {},
    Semey: {},
    Shymkent: {},
    Taraz: {},
    Temirtau: {},
  },
  KENYA: {
    citiesNames: ["Kisumu", "Mombasa", "Nairobi"],
    Kisumu: {},
    Mombasa: {},
    Nairobi: {},
  },
  KUWAIT: {
    citiesNames: [
      "Abdali",
      "Ahmadi",
      "Failaka",
      "Jahra",
      "Kuwait",
      "Nweasib",
      "Salmi",
      "Wafra",
    ],
    Abdali: {},
    Ahmadi: {},
    Failaka: {},
    Jahra: {},
    Kuwait: {},
    Nweasib: {},
    Salmi: {},
    Wafra: {},
  },
  KYRGYZSTAN: {
    citiesNames: ["Bishkek"],
    Bishkek: {},
  },
  LAOS: {
    citiesNames: ["Vientiane"],
    Vientiane: {},
  },
  LATVIA: {
    citiesNames: [
      "Cesis",
      "Daugavpils",
      "Jekabpils",
      "Jelgava",
      "Jurmala",
      "Liepaja",
      "Ogre",
      "Rezekne",
      "Riga",
      "Valmiera",
      "Ventspils",
    ],
    Cesis: {},
    Daugavpils: {},
    Jekabpils: {},
    Jelgava: {},
    Jurmala: {},
    Liepaja: {},
    Ogre: {},
    Rezekne: {},
    Riga: {},
    Valmiera: {},
    Ventspils: {},
  },
  LEBANON: {
    citiesNames: ["Al_Marj", "Balbak", "Beirut", "Jabal_Sultan", "Trabulus"],
    Al_Marj: {},
    Balbak: {},
    Beirut: {},
    Jabal_Sultan: {},
    Trabulus: {},
  },
  LIBERIA: {
    citiesNames: ["Monrovia"],
    Monrovia: {},
  },
  LIBYA: {
    citiesNames: [
      "Ajdabiya",
      "Al_Bayda",
      "Az_Zawiyah",
      "Aziziyah",
      "Bani_Walid",
      "Benghazi",
      "Bin_Jawad",
      "Breaga",
      "Derna",
      "Ghadames",
      "Gheryan",
      "Hun",
      "Jadu",
      "Jalu",
      "Khoms",
      "Kufrah",
      "Misrata",
      "Murzuq",
      "Nalut",
      "Ras_Jdear",
      "Ras_Lanouf",
      "Sebha",
      "Sibrata",
      "Sirt",
      "Surman",
      "Taragen",
      "Tarhuna",
      "Tripoli",
      "Tubroq",
      "Ubari",
      "Yefren",
      "Zintan",
      "Zliten",
      "Zuwara",
    ],
    Ajdabiya: {},
    Al_Bayda: {},
    Az_Zawiyah: {},
    Aziziyah: {},
    Bani_Walid: {},
    Benghazi: {},
    Bin_Jawad: {},
    Breaga: {},
    Derna: {},
    Ghadames: {},
    Gheryan: {},
    Hun: {},
    Jadu: {},
    Jalu: {},
    Khoms: {},
    Kufrah: {},
    Misrata: {},
    Murzuq: {},
    Nalut: {},
    Ras_Jdear: {},
    Ras_Lanouf: {},
    Sebha: {},
    Sibrata: {},
    Sirt: {},
    Surman: {},
    Taragen: {},
    Tarhuna: {},
    Tripoli: {},
    Tubroq: {},
    Ubari: {},
    Yefren: {},
    Zintan: {},
    Zliten: {},
    Zuwara: {},
  },
  LITHUANIA: {
    citiesNames: [
      "Alytus",
      "Druskininkai",
      "Jonava",
      "Kaunas",
      "Kedainiai",
      "Klaipeda",
      "Kretinga",
      "Marijampole",
      "Mazeikiai",
      "Panevezys",
      "Plunge",
      "Radviliskis",
      "Siauliai",
      "Silute",
      "Taurage",
      "Telsiai",
      "Ukmerge",
      "Utena",
      "Vilnius",
      "Visaginas",
    ],
    Alytus: {},
    Druskininkai: {},
    Jonava: {},
    Kaunas: {},
    Kedainiai: {},
    Klaipeda: {},
    Kretinga: {},
    Marijampole: {},
    Mazeikiai: {},
    Panevezys: {},
    Plunge: {},
    Radviliskis: {},
    Siauliai: {},
    Silute: {},
    Taurage: {},
    Telsiai: {},
    Ukmerge: {},
    Utena: {},
    Vilnius: {},
    Visaginas: {},
  },
  LUXEMBOURG: {
    citiesNames: [
      "_Bascharage",
      "_Belvaux",
      "_Bettembourg",
      "_Diekirch",
      "_Differdange",
      "_Dudelange",
      "_Echternach",
      "_Esch_Alzette_",
      "_Ettelbruck",
      "_Luxembourg_",
      "_Mamer",
      "_Petange",
      "_Schifflange",
      "_Soleuvre",
      "_Strassen",
      "_Wiltz",
    ],
    _Bascharage: {},
    _Belvaux: {},
    _Bettembourg: {},
    _Diekirch: {},
    _Differdange: {},
    _Dudelange: {},
    _Echternach: {},
    _Esch_Alzette_: {},
    _Ettelbruck: {},
    _Luxembourg_: {},
    _Mamer: {},
    _Petange: {},
    _Schifflange: {},
    _Soleuvre: {},
    _Strassen: {},
    _Wiltz: {},
  },
  MADAGASCAR: {
    citiesNames: ["Majunga", "Nossi_be", "Tamatave"],
    Majunga: {},
    Nossi_be: {},
    Tamatave: {},
  },
  MALAWI: {
    citiesNames: ["Blantyre", "Lilongwe"],
    Blantyre: {},
    Lilongwe: {},
  },
  MALAYSIA: {
    citiesNames: [
      "Johore_Bahru",
      "Kuala_Lumpur",
      "Kuching",
      "Miri",
      "Penang",
      "Sandakan",
    ],
    Johore_Bahru: {},
    Kuala_Lumpur: {},
    Kuching: {},
    Miri: {},
    Penang: {},
    Sandakan: {},
  },
  MALDIVES: {
    citiesNames: ["Male"],
    Male: {},
  },
  MALI: {
    citiesNames: ["Bamako", "Mopti"],
    Bamako: {},
    Mopti: {},
  },
  MALTA: {
    citiesNames: ["Malta"],
    Malta: {},
  },
  MAURITANIA: {
    citiesNames: ["Kaedi", "Nouadhibou", "Nouakchott"],
    Kaedi: {},
    Nouadhibou: {},
    Nouakchott: {},
  },
  MAURITIUS: {
    citiesNames: ["Mauritius"],
    Mauritius: {},
  },
  MEXICO: {
    citiesNames: [
      "Acapulco",
      "Campeche",
      "Can_Cun",
      "Chetumal",
      "Chihuahua",
      "Ciudad_Juarez",
      "Ciudad_Obregon",
      "Culiacan",
      "Durango",
      "Guaymas",
      "Mexico_City",
    ],
    Acapulco: {},
    Campeche: {},
    Can_Cun: {},
    Chetumal: {},
    Chihuahua: {},
    Ciudad_Juarez: {},
    Ciudad_Obregon: {},
    Culiacan: {},
    Durango: {},
    Guaymas: {},
    Mexico_City: {},
  },
  MOROCCO: {
    citiesNames: [
      "Agadir",
      "Al_Hoceima",
      "Casablanca",
      "Dakhla",
      "Fez",
      "Laayoune",
      "Marrakech",
      "Oujda",
      "Rabat",
      "Sidi_Ifni",
      "Tangier",
    ],
    Agadir: {},
    Al_Hoceima: {},
    Casablanca: {},
    Dakhla: {},
    Fez: {},
    Laayoune: {},
    Marrakech: {},
    Oujda: {},
    Rabat: {},
    Sidi_Ifni: {},
    Tangier: {},
  },
  MOZAMBIQUE: {
    citiesNames: ["Beira", "Maputo", "Mocimboa_Praia", "Nampula"],
    Beira: {},
    Maputo: {},
    Mocimboa_Praia: {},
    Nampula: {},
  },
  MYANMAR: {
    citiesNames: ["Yangon"],
    Yangon: {},
  },
  NAMIBIA: {
    citiesNames: ["Grootfontein", "Keetmanshoop", "Windhoek"],
    Grootfontein: {},
    Keetmanshoop: {},
    Windhoek: {},
  },
  NEPAL: {
    citiesNames: ["Kathmandu"],
    Kathmandu: {},
  },
  NETHERLANDS: {
    citiesNames: [
      "Almere",
      "Amersfoort",
      "Amsterdam_",
      "Apeldoorn_",
      "Arnhem",
      "Breda",
      "Dordrecht",
      "Eindhoven",
      "Enschede",
      "Groningen",
      "Haarlem",
      "Haarlemmermeer",
      "Hertogenbosch",
      "Maastricht",
      "Nijmegen",
      "Rotterdam",
      "The_Hague",
      "Tilburg",
      "Utrecht",
      "Zaanstad",
    ],
    Almere: {},
    Amersfoort: {},
    Amsterdam_: {},
    Apeldoorn_: {},
    Arnhem: {},
    Breda: {},
    Dordrecht: {},
    Eindhoven: {},
    Enschede: {},
    Groningen: {},
    Haarlem: {},
    Haarlemmermeer: {},
    Hertogenbosch: {},
    Maastricht: {},
    Nijmegen: {},
    Rotterdam: {},
    The_Hague: {},
    Tilburg: {},
    Utrecht: {},
    Zaanstad: {},
  },
  NEW: {
    citiesNames: [
      "CALEDONIA_Noumea",
      "ZEALAND_Auckland",
      "ZEALAND_Christchurch",
      "ZEALAND_Wellington",
    ],
    CALEDONIA_Noumea: {},
    ZEALAND_Auckland: {},
    ZEALAND_Christchurch: {},
    ZEALAND_Wellington: {},
  },
  NICARAGUA: {
    citiesNames: ["Managua"],
    Managua: {},
  },
  NIGER: {
    citiesNames: ["Agades", "Niamey"],
    Agades: {},
    Niamey: {},
  },
  NIGERIA: {
    citiesNames: [
      "Abuja",
      "Akure",
      "Bauchi",
      "Benin_City",
      "Calabar",
      "Enugu",
      "Ilorin",
      "Jos",
      "Kaduna",
      "Kano",
      "Lagos",
      "Maiduguri",
      "Port_Harcourt",
      "Sokoto",
      "Yola",
    ],
    Abuja: {},
    Akure: {},
    Bauchi: {},
    Benin_City: {},
    Calabar: {},
    Enugu: {},
    Ilorin: {},
    Jos: {},
    Kaduna: {},
    Kano: {},
    Lagos: {},
    Maiduguri: {},
    Port_Harcourt: {},
    Sokoto: {},
    Yola: {},
  },
  NORWAY: {
    citiesNames: [
      "Akershus",
      "Arendal",
      "Bergen",
      "Bodo",
      "Drammen",
      "Fredrikstad_Sarpsborg",
      "Halden",
      "Hamar",
      "Harstad",
      "Haugesund",
      "Kristiansand",
      "Larvik",
      "Moss",
      "Oslo_",
      "Porsgrunn_Skien",
      "Sandefjord",
      "Stavanger",
      "Tonsberg",
      "Troms",
      "Trondheim",
      "lesund",
    ],
    Akershus: {},
    Arendal: {},
    Bergen: {},
    Bodo: {},
    Drammen: {},
    Fredrikstad_Sarpsborg: {},
    Halden: {},
    Hamar: {},
    Harstad: {},
    Haugesund: {},
    Kristiansand: {},
    Larvik: {},
    Moss: {},
    Oslo_: {},
    Porsgrunn_Skien: {},
    Sandefjord: {},
    Stavanger: {},
    Tonsberg: {},
    Troms: {},
    Trondheim: {},
    lesund: {},
  },
  OMAN: {
    citiesNames: ["Jabal_Shams", "Muscat", "Salalah"],
    Jabal_Shams: {},
    Muscat: {},
    Salalah: {},
  },
  PAKISTAN: {
    citiesNames: [
      "Faisalabad",
      "Hyderabad",
      "Islamabad",
      "Karachi",
      "Lahore",
      "Mohenjodaro",
      "Multan",
      "Nawabshah",
      "Peshawar",
    ],
    Faisalabad: {},
    Hyderabad: {},
    Islamabad: {},
    Karachi: {},
    Lahore: {},
    Mohenjodaro: {},
    Multan: {},
    Nawabshah: {},
    Peshawar: {},
  },
  PALAU: {
    citiesNames: ["Koror"],
    Koror: {},
  },
  PALESTINE: {
    citiesNames: [
      "Affuleh",
      "Akka",
      "Al_Khalil",
      "Al_Khalsah_Qiryat_Shemona",
      "Al_Led_War_Ramleh",
      "Al_Quds",
      "Al_Samua",
      "An_Nasrah",
      "Areeha",
      "Ashdod",
      "Asqalan",
      "Bait_Lahem",
      "Beer_Al_Sabea",
      "Beesan",
      "Dear_Al_Balah",
      "Ghazza",
      "Haifa",
      "Jabal_Al_Jarmaq",
      "Jeneen",
      "Khan_Yunis",
      "Nablus",
      "Qalqelyah",
      "Rafah",
      "Ramallah",
      "Safad",
      "Tabareyyah",
      "Toolkarem",
      "Umm_Al_Rashrash_Elat",
      "Umm_Khalid_Natanya",
      "Ummel_Fahem",
      "Yafa",
      "Yatta",
    ],
    Affuleh: {},
    Akka: {},
    Al_Khalil: {},
    Al_Khalsah_Qiryat_Shemona: {},
    Al_Led_War_Ramleh: {},
    Al_Quds: {},
    Al_Samua: {},
    An_Nasrah: {},
    Areeha: {},
    Ashdod: {},
    Asqalan: {},
    Bait_Lahem: {},
    Beer_Al_Sabea: {},
    Beesan: {},
    Dear_Al_Balah: {},
    Ghazza: {},
    Haifa: {},
    Jabal_Al_Jarmaq: {},
    Jeneen: {},
    Khan_Yunis: {},
    Nablus: {},
    Qalqelyah: {},
    Rafah: {},
    Ramallah: {},
    Safad: {},
    Tabareyyah: {},
    Toolkarem: {},
    Umm_Al_Rashrash_Elat: {},
    Umm_Khalid_Natanya: {},
    Ummel_Fahem: {},
    Yafa: {},
    Yatta: {},
  },
  PANAMA: {
    citiesNames: ["Fort_Kobbe", "Panama_City"],
    Fort_Kobbe: {},
    Panama_City: {},
  },
  PARAGUAY: {
    citiesNames: ["Asuncion"],
    Asuncion: {},
  },
  PERU: {
    citiesNames: [
      "Arequipa",
      "Chiclayo",
      "Cuzco",
      "Iquitos",
      "Lima",
      "Piura",
      "Pucallpa",
      "Tacna",
      "Talara",
      "Trujillo",
    ],
    Arequipa: {},
    Chiclayo: {},
    Cuzco: {},
    Iquitos: {},
    Lima: {},
    Piura: {},
    Pucallpa: {},
    Tacna: {},
    Talara: {},
    Trujillo: {},
  },
  PHILIPPINES: {
    citiesNames: [
      "Cagayan",
      "Davao",
      "Iloilo",
      "Luzon_Island",
      "Mactan_Island",
      "Manila",
      "Marawi",
    ],
    Cagayan: {},
    Davao: {},
    Iloilo: {},
    Luzon_Island: {},
    Mactan_Island: {},
    Manila: {},
    Marawi: {},
  },
  POLAND: {
    citiesNames: [
      "Bialystok",
      "Bydgoszcz",
      "Bytom",
      "Czestochowa",
      "Gdansk",
      "Gdynia_",
      "Gliwice_",
      "Katowice",
      "Kielce",
      "Krakow",
      "Lodz",
      "Lublin",
      "Poznan",
      "Radom",
      "Sosnowiec",
      "Szczecin",
      "Torun",
      "Warsaw",
      "Wroclaw",
      "Zabrze",
    ],
    Bialystok: {},
    Bydgoszcz: {},
    Bytom: {},
    Czestochowa: {},
    Gdansk: {},
    Gdynia_: {},
    Gliwice_: {},
    Katowice: {},
    Kielce: {},
    Krakow: {},
    Lodz: {},
    Lublin: {},
    Poznan: {},
    Radom: {},
    Sosnowiec: {},
    Szczecin: {},
    Torun: {},
    Warsaw: {},
    Wroclaw: {},
    Zabrze: {},
  },
  PORTUGAL: {
    citiesNames: ["Faro", "Lisbon", "Porto"],
    Faro: {},
    Lisbon: {},
    Porto: {},
  },
  PUERTO: {
    citiesNames: ["RICO_Aguadilla", "RICO_Roosevelt_Roads"],
    RICO_Aguadilla: {},
    RICO_Roosevelt_Roads: {},
  },
  QATAR: {
    citiesNames: [
      "Al_Khor",
      "Doha",
      "Dukhan",
      "Madinet_Al_Shamal",
      "Mseaeed",
      "Ras_Laffan",
      "Shahaniyya",
      "Wakra",
    ],
    Al_Khor: {},
    Doha: {},
    Dukhan: {},
    Madinet_Al_Shamal: {},
    Mseaeed: {},
    Ras_Laffan: {},
    Shahaniyya: {},
    Wakra: {},
  },
  ROMANIA: {
    citiesNames: [
      "Arad",
      "Bucharest",
      "Constanta",
      "Sibiu",
      "Timisoara",
      "Tulcea",
    ],
    Arad: {},
    Bucharest: {},
    Constanta: {},
    Sibiu: {},
    Timisoara: {},
    Tulcea: {},
  },
  RUSSIA: {
    citiesNames: [
      "Astrakhan_",
      "Ekaternburgh",
      "Moscow",
      "Tsumada",
      "Vladivostok",
    ],
    Astrakhan_: {},
    Ekaternburgh: {},
    Moscow: {},
    Tsumada: {},
    Vladivostok: {},
  },
  RWANDA: {
    citiesNames: ["Kigali"],
    Kigali: {},
  },
  Refraction: {
    citiesNames: [],
  },
  Refraction2: {
    citiesNames: [],
  },
  SAUDI: {
    citiesNames: [
      "ARABIA_Abha",
      "ARABIA_Abu_Arish",
      "ARABIA_Alras",
      "ARABIA_Arar",
      "ARABIA_Baha",
      "ARABIA_Baish",
      "ARABIA_Barzayn",
      "ARABIA_Bisha",
      "ARABIA_Bukayriyah",
      "ARABIA_Buqayq",
      "ARABIA_Buraydah",
      "ARABIA_Dammam",
      "ARABIA_Dawadimi",
      "ARABIA_Dhahran",
      "ARABIA_Fegrah",
      "ARABIA_Hafar_Al_Batin",
      "ARABIA_Hail",
      "ARABIA_Halet_Ammar",
      "ARABIA_Hanidh",
      "ARABIA_Hawtit_Sudear",
      "ARABIA_Hofuf",
      "ARABIA_Jeddah",
      "ARABIA_Jizan",
      "ARABIA_Jouf",
      "ARABIA_Jubail",
      "ARABIA_Khamasin",
      "ARABIA_Khamis_Mushait",
      "ARABIA_Khobar",
      "ARABIA_Madinah",
      "ARABIA_Majmaah",
      "ARABIA_Makkah",
      "ARABIA_Musayjid",
      "ARABIA_Najran",
      "ARABIA_Qaisumah",
      "ARABIA_Qaryat_Al_Ulia",
      "ARABIA_Qassim",
      "ARABIA_Qatif",
      "ARABIA_Qrayyat",
      "ARABIA_Rabigh",
      "ARABIA_Rafha",
      "ARABIA_Ranyah",
      "ARABIA_Ras_Tunnurah",
      "ARABIA_Riyadh",
      "ARABIA_Sakakah",
      "ARABIA_Shaqra",
      "ARABIA_Sharurah",
      "ARABIA_Sudear",
      "ARABIA_Tabuk",
      "ARABIA_Taif",
      "ARABIA_Tayma",
      "ARABIA_Turaif",
      "ARABIA_Umlaj",
      "ARABIA_Unayzah",
      "ARABIA_Wajh",
      "ARABIA_Yanbo",
    ],
    ARABIA_Abha: {},
    ARABIA_Abu_Arish: {},
    ARABIA_Alras: {},
    ARABIA_Arar: {},
    ARABIA_Baha: {},
    ARABIA_Baish: {},
    ARABIA_Barzayn: {},
    ARABIA_Bisha: {},
    ARABIA_Bukayriyah: {},
    ARABIA_Buqayq: {},
    ARABIA_Buraydah: {},
    ARABIA_Dammam: {},
    ARABIA_Dawadimi: {},
    ARABIA_Dhahran: {},
    ARABIA_Fegrah: {},
    ARABIA_Hafar_Al_Batin: {},
    ARABIA_Hail: {},
    ARABIA_Halet_Ammar: {},
    ARABIA_Hanidh: {},
    ARABIA_Hawtit_Sudear: {},
    ARABIA_Hofuf: {},
    ARABIA_Jeddah: {},
    ARABIA_Jizan: {},
    ARABIA_Jouf: {},
    ARABIA_Jubail: {},
    ARABIA_Khamasin: {},
    ARABIA_Khamis_Mushait: {},
    ARABIA_Khobar: {},
    ARABIA_Madinah: {},
    ARABIA_Majmaah: {},
    ARABIA_Makkah: {},
    ARABIA_Musayjid: {},
    ARABIA_Najran: {},
    ARABIA_Qaisumah: {},
    ARABIA_Qaryat_Al_Ulia: {},
    ARABIA_Qassim: {},
    ARABIA_Qatif: {},
    ARABIA_Qrayyat: {},
    ARABIA_Rabigh: {},
    ARABIA_Rafha: {},
    ARABIA_Ranyah: {},
    ARABIA_Ras_Tunnurah: {},
    ARABIA_Riyadh: {},
    ARABIA_Sakakah: {},
    ARABIA_Shaqra: {},
    ARABIA_Sharurah: {},
    ARABIA_Sudear: {},
    ARABIA_Tabuk: {},
    ARABIA_Taif: {},
    ARABIA_Tayma: {},
    ARABIA_Turaif: {},
    ARABIA_Umlaj: {},
    ARABIA_Unayzah: {},
    ARABIA_Wajh: {},
    ARABIA_Yanbo: {},
  },
  SENEGAL: {
    citiesNames: ["Dakar"],
    Dakar: {},
  },
  SIERRA: {
    citiesNames: ["LEONE_Freetown"],
    LEONE_Freetown: {},
  },
  SINGAPORE: {
    citiesNames: ["Singapore"],
    Singapore: {},
  },
  SLOVAKIA: {
    citiesNames: ["Bratislava", "Prague"],
    Bratislava: {},
    Prague: {},
  },
  SOLOMON: {
    citiesNames: ["ISLAND_Honiara"],
    ISLAND_Honiara: {},
  },
  SOMALIA: {
    citiesNames: ["Hargeisa", "Mogadishu"],
    Hargeisa: {},
    Mogadishu: {},
  },
  SOUTH: {
    citiesNames: [
      "AFRICA_Bloemfontein",
      "AFRICA_Capetown",
      "AFRICA_Durban",
      "AFRICA_George",
      "AFRICA_Johannesburg",
      "AFRICA_Kimberley",
      "AFRICA_Pietersburg",
      "AFRICA_Pretoria",
      "AFRICA_Upington",
      "AFRICA_Welkom",
      "KOREA_Cheju",
      "KOREA_Kusan",
      "KOREA_Kwangju",
      "KOREA_Osan",
      "KOREA_Pusan",
      "KOREA_Seoul",
      "KOREA_Taegu",
    ],
    AFRICA_Bloemfontein: {},
    AFRICA_Capetown: {},
    AFRICA_Durban: {},
    AFRICA_George: {},
    AFRICA_Johannesburg: {},
    AFRICA_Kimberley: {},
    AFRICA_Pietersburg: {},
    AFRICA_Pretoria: {},
    AFRICA_Upington: {},
    AFRICA_Welkom: {},
    KOREA_Cheju: {},
    KOREA_Kusan: {},
    KOREA_Kwangju: {},
    KOREA_Osan: {},
    KOREA_Pusan: {},
    KOREA_Seoul: {},
    KOREA_Taegu: {},
  },
  SPAIN: {
    citiesNames: [
      "Barcelona",
      "Alicante",
      "Almeria",
      "Asturias",
      "Badajoz",
      "Bilbao",
      "Fuerteventura",
      "Gerona",
      "Gran_Canaria",
      "Granada",
      "Ibiza",
      "Ishbilia",
      "Jerez_Frontera",
      "Lanzarote",
      "Madrid",
      "Mahon",
      "Malaga",
      "Moron",
      "Murcia",
      "Palma_Mallorca",
      "Pamplona",
      "Reus",
      "Santander",
      "Seville",
      "Tenerife",
      "Valencia",
      "Valladolid",
      "Vigo",
      "Vitoria",
      "Zaragoza",
    ],
    Barcelona: {},
    Alicante: {},
    Almeria: {},
    Asturias: {},
    Badajoz: {},
    Bilbao: {},
    Fuerteventura: {},
    Gerona: {},
    Gran_Canaria: {},
    Granada: {},
    Ibiza: {},
    Ishbilia: {},
    Jerez_Frontera: {},
    Lanzarote: {},
    Madrid: {},
    Mahon: {},
    Malaga: {},
    Moron: {},
    Murcia: {},
    Palma_Mallorca: {},
    Pamplona: {},
    Reus: {},
    Santander: {},
    Seville: {},
    Tenerife: {},
    Valencia: {},
    Valladolid: {},
    Vigo: {},
    Vitoria: {},
    Zaragoza: {},
  },
  SRI: {
    citiesNames: ["LANKA_Colombo", "LANKA_Jaffna"],
    LANKA_Colombo: {},
    LANKA_Jaffna: {},
  },
  SUDAN: {
    citiesNames: ["El_Obeid", "Khartoum", "Port_Sudan"],
    El_Obeid: {},
    Khartoum: {},
    Port_Sudan: {},
  },
  SURINAME: {
    citiesNames: ["Paramaribo"],
    Paramaribo: {},
  },
  SWEDEN: {
    citiesNames: [
      "Boras",
      "Eskilstuna",
      "Gavle",
      "Gothenburg",
      "Halmstad",
      "Helsingborg",
      "Jonkoping",
      "Karlstad",
      "Linkoping",
      "Malmo",
      "Norrkoping",
      "Orebro",
      "Sodertalje",
      "Stockholm",
      "Taby",
      "Umea",
      "Uppsala",
      "Vasteras",
      "Vaxjo",
    ],
    Boras: {},
    Eskilstuna: {},
    Gavle: {},
    Gothenburg: {},
    Halmstad: {},
    Helsingborg: {},
    Jonkoping: {},
    Karlstad: {},
    Linkoping: {},
    Malmo: {},
    Norrkoping: {},
    Orebro: {},
    Sodertalje: {},
    Stockholm: {},
    Taby: {},
    Umea: {},
    Uppsala: {},
    Vasteras: {},
    Vaxjo: {},
  },
  SWITZERLAND: {
    citiesNames: ["Basle", "Geneva", "Lugano", "Zurich"],
    Basle: {},
    Geneva: {},
    Lugano: {},
    Zurich: {},
  },
  SYRIA: {
    citiesNames: [
      "Aleppo",
      "Ar_Raqqa",
      "Damascus",
      "Deir_Ezzor",
      "Kameshli",
      "Latheqeyah",
    ],
    Aleppo: {},
    Ar_Raqqa: {},
    Damascus: {},
    Deir_Ezzor: {},
    Kameshli: {},
    Latheqeyah: {},
  },
  TAIWAN: {
    citiesNames: [
      "Chiayi",
      "Hualien",
      "Kaohsiung",
      "Makung",
      "Tainan",
      "Taipei",
      "Taitung",
    ],
    Chiayi: {},
    Hualien: {},
    Kaohsiung: {},
    Makung: {},
    Tainan: {},
    Taipei: {},
    Taitung: {},
  },
  TAJIKISTAN: {
    citiesNames: ["Dushanbe"],
    Dushanbe: {},
  },
  TANZANIA: {
    citiesNames: [
      "Dar_Es_Salaam",
      "Dodoma",
      "Kilimanjaro",
      "Mtwara",
      "Mwanza",
      "Zanzibar",
    ],
    Dar_Es_Salaam: {},
    Dodoma: {},
    Kilimanjaro: {},
    Mtwara: {},
    Mwanza: {},
    Zanzibar: {},
  },
  THAILAND: {
    citiesNames: [
      "Bangkok",
      "Chiang_Mai",
      "Hat_Yai",
      "Phitsanulok",
      "Phuket",
      "Takhli",
      "Udon_Thani",
      "Utapao",
    ],
    Bangkok: {},
    Chiang_Mai: {},
    Hat_Yai: {},
    Phitsanulok: {},
    Phuket: {},
    Takhli: {},
    Udon_Thani: {},
    Utapao: {},
  },
  TOGO: {
    citiesNames: ["Lome"],
    Lome: {},
  },
  TUNISIA: {
    citiesNames: [
      "Bizerte",
      "Gabes",
      "Gafsa",
      "Hammamet",
      "Jarba_Hawmet_Assuq",
      "Jarjis",
      "Kasserine",
      "Mahdiya",
      "Monastir",
      "Napuel",
      "Qayrawan",
      "Sfax",
      "Sidi_Bouzid",
      "Sousse",
      "Tabarqa",
      "Tozeur",
      "Tunis",
    ],
    Bizerte: {},
    Gabes: {},
    Gafsa: {},
    Hammamet: {},
    Jarba_Hawmet_Assuq: {},
    Jarjis: {},
    Kasserine: {},
    Mahdiya: {},
    Monastir: {},
    Napuel: {},
    Qayrawan: {},
    Sfax: {},
    Sidi_Bouzid: {},
    Sousse: {},
    Tabarqa: {},
    Tozeur: {},
    Tunis: {},
  },
  TURKEY: {
    citiesNames: [
      "Adana",
      "Ankara",
      "Antalya",
      "Balikesir",
      "Dalaman",
      "Diyarbakir",
      "Erzurum",
      "Gaziantep",
      "Istanbul",
      "Izmir",
      "Kayseri",
      "Konya",
      "Malatya",
      "Sivas",
      "Van",
    ],
    Adana: {},
    Ankara: {},
    Antalya: {},
    Balikesir: {},
    Dalaman: {},
    Diyarbakir: {},
    Erzurum: {},
    Gaziantep: {},
    Istanbul: {},
    Izmir: {},
    Kayseri: {},
    Konya: {},
    Malatya: {},
    Sivas: {},
    Van: {},
  },
  TURKMENISTAN: {
    citiesNames: ["Ashgabat"],
    Ashgabat: {},
  },
  UAE: {
    citiesNames: [
      "AD_Abu_Dhabi",
      "AD_Ain",
      "AD_Al_Sala",
      "AD_Arzena",
      "AD_Asab",
      "AD_Bida_Mutawaah",
      "AD_Bu_Hasa",
      "AD_Dabaeyeh",
      "AD_Das",
      "AD_Dilma",
      "AD_Gafay",
      "AD_Ghagha",
      "AD_Ghiyathi",
      "AD_Ghweafat",
      "AD_Gooa",
      "AD_Hafit",
      "AD_Hamim",
      "AD_Hear",
      "AD_Jabal_Dhannah",
      "AD_Khatam",
      "AD_Madinat_Zayed",
      "AD_Mafraq",
      "AD_Marfa",
      "AD_Mizyad",
      "AD_Mkhearez",
      "AD_Musaffah",
      "AD_Mzearaah",
      "AD_Ruweas",
      "AD_Shahamah",
      "AD_Shweab",
      "AD_Sir_Bani_Yas",
      "AD_Sweahan",
      "AD_Taref",
      "AD_Umm_Hisn",
      "AD_Umm_Zmool",
      "AD_Wegen",
      "AD_Yahar",
      "AD_Zirkowa",
      "AJM_Ajman",
      "AJM_Masfut",
      "DUB_Dubai",
      "DUB_Hatta",
      "DUB_Jabal_Ali",
      "FUJ_Agga",
      "FUJ_Bidya",
      "FUJ_Bithna",
      "FUJ_Diba",
      "FUJ_Fujearah",
      "FUJ_Habhab",
      "FUJ_Masafi",
      "FUJ_Qidfa",
      "FUJ_Siji",
      "FUJ_Tweyyeen",
      "RAK_Athen",
      "RAK_Hwealat",
      "RAK_Masafi",
      "RAK_Mneay",
      "RAK_Rasel_Kheamah",
      "RAK_Shaam",
      "RAK_Shoakah",
      "RAK_Tonb_Alkubra",
      "SHJ_Abu_Musa",
      "SHJ_Dhead",
      "SHJ_Diba",
      "SHJ_Kalba",
      "SHJ_Khour_Fakkan",
      "SHJ_Sharjah",
      "SHJ_Sir_Bo_Nair",
      "UMQ_Ummel_Quwean",
    ],
    AD_Abu_Dhabi: {},
    AD_Ain: {},
    AD_Al_Sala: {},
    AD_Arzena: {},
    AD_Asab: {},
    AD_Bida_Mutawaah: {},
    AD_Bu_Hasa: {},
    AD_Dabaeyeh: {},
    AD_Das: {},
    AD_Dilma: {},
    AD_Gafay: {},
    AD_Ghagha: {},
    AD_Ghiyathi: {},
    AD_Ghweafat: {},
    AD_Gooa: {},
    AD_Hafit: {},
    AD_Hamim: {},
    AD_Hear: {},
    AD_Jabal_Dhannah: {},
    AD_Khatam: {},
    AD_Madinat_Zayed: {},
    AD_Mafraq: {},
    AD_Marfa: {},
    AD_Mizyad: {},
    AD_Mkhearez: {},
    AD_Musaffah: {},
    AD_Mzearaah: {},
    AD_Ruweas: {},
    AD_Shahamah: {},
    AD_Shweab: {},
    AD_Sir_Bani_Yas: {},
    AD_Sweahan: {},
    AD_Taref: {},
    AD_Umm_Hisn: {},
    AD_Umm_Zmool: {},
    AD_Wegen: {},
    AD_Yahar: {},
    AD_Zirkowa: {},
    AJM_Ajman: {},
    AJM_Masfut: {},
    DUB_Dubai: {},
    DUB_Hatta: {},
    DUB_Jabal_Ali: {},
    FUJ_Agga: {},
    FUJ_Bidya: {},
    FUJ_Bithna: {},
    FUJ_Diba: {},
    FUJ_Fujearah: {},
    FUJ_Habhab: {},
    FUJ_Masafi: {},
    FUJ_Qidfa: {},
    FUJ_Siji: {},
    FUJ_Tweyyeen: {},
    RAK_Athen: {},
    RAK_Hwealat: {},
    RAK_Masafi: {},
    RAK_Mneay: {},
    RAK_Rasel_Kheamah: {},
    RAK_Shaam: {},
    RAK_Shoakah: {},
    RAK_Tonb_Alkubra: {},
    SHJ_Abu_Musa: {},
    SHJ_Dhead: {},
    SHJ_Diba: {},
    SHJ_Kalba: {},
    SHJ_Khour_Fakkan: {},
    SHJ_Sharjah: {},
    SHJ_Sir_Bo_Nair: {},
    UMQ_Ummel_Quwean: {},
  },
  UGANDA: {
    citiesNames: ["Entebbe"],
    Entebbe: {},
  },
  UK: {
    citiesNames: [
      "Birmingham",
      "Bradford",
      "Bristol_",
      "Coventry_",
      "Derby_",
      "Hull",
      "Leeds",
      "Leicester_",
      "Liverpool",
      "London",
      "Manchester",
      "Nottingham",
      "Plymouth",
      "Sheffield_",
      "Stoke_on_Trent_",
      "Wolverhampton",
    ],
    Birmingham: {},
    Bradford: {},
    Bristol_: {},
    Coventry_: {},
    Derby_: {},
    Hull: {},
    Leeds: {},
    Leicester_: {},
    Liverpool: {},
    London: {},
    Manchester: {},
    Nottingham: {},
    Plymouth: {},
    Sheffield_: {},
    Stoke_on_Trent_: {},
    Wolverhampton: {},
  },
  UKRAINE: {
    citiesNames: [
      "Cherkasy",
      "Chernigov",
      "Dnipropetrovsk",
      "Donetsk",
      "Kharkov",
      "Kherson",
      "Kiev",
      "Kryvyi_Rih",
      "Luhansk",
      "Lviv",
      "Makiivka",
      "Mariupol",
      "Mykolaiv",
      "Odesa",
      "Poltava",
      "Sevastopol",
      "Simferopol",
      "Sumy",
      "Vinnytsia",
      "Zaporizhzhya",
    ],
    Cherkasy: {},
    Chernigov: {},
    Dnipropetrovsk: {},
    Donetsk: {},
    Kharkov: {},
    Kherson: {},
    Kiev: {},
    Kryvyi_Rih: {},
    Luhansk: {},
    Lviv: {},
    Makiivka: {},
    Mariupol: {},
    Mykolaiv: {},
    Odesa: {},
    Poltava: {},
    Sevastopol: {},
    Simferopol: {},
    Sumy: {},
    Vinnytsia: {},
    Zaporizhzhya: {},
  },
  URUGUAY: {
    citiesNames: ["Montevideo"],
    Montevideo: {},
  },
  USA: {
    citiesNames: [
      "AK_Adak_Island",
      "AK_Anchorage",
      "AK_Annette_Island",
      "AK_Barrow",
      "AK_Bethel",
      "AK_Big_Delta",
      "AK_Brooks_Lake",
      "AK_Cape_Sarichef",
      "AK_Cordova",
      "AK_Dillingham",
      "AK_Dolomi",
      "AK_Fairbanks",
      "AK_Galena",
      "AK_Homer",
      "AK_Juneau",
      "AK_Kenai",
      "AK_Ketchikan",
      "AK_King_Salmon",
      "AK_Kodiak",
      "AK_Kotzebue",
      "AK_Mcgrath",
      "AK_Nome",
      "AK_Northway",
      "AK_Prudhoe_Bay",
      "AK_Shemya",
      "AK_Sitka",
      "AK_Valdez",
      "AK_Yakutat",
      "AL_Anniston",
      "AL_Dothan",
      "AL_Gadsden",
      "AL_Hamilton",
      "AL_Huntsville",
      "AL_Mobile",
      "AL_Montgomery",
      "AL_Muscle_Shoals",
      "AL_Selma",
      "AL_Talladega",
      "AL_Tuscaloosa",
      "AR_Batesville",
      "AR_Blytheville",
      "AR_Buenos_Aires",
      "AR_Camden",
      "AR_Fort_Smith",
      "AR_Harrison",
      "AR_Hot_Springs",
      "AR_Jacksonville",
      "AR_Jonesboro",
      "AR_Little_Rock",
      "AR_Morrilton",
      "AR_Pine_Bluff",
      "AR_Resistencia",
      "AR_Rio_Cuarto",
      "AR_Rio_Grande",
      "AR_San_Carlos_Debar",
      "AR_Texarkana",
      "AR_Walnut_Ridge",
      "AZ_Casa_Grande",
      "AZ_Cottonwood",
      "AZ_Douglas",
      "AZ_Flagstaff",
      "AZ_Goodyear",
      "AZ_Grand_Canyon",
      "AZ_Kingman",
      "AZ_Lake_Havasu_City",
      "AZ_Marana",
      "AZ_Nogales",
      "AZ_Page",
      "AZ_Phoenix",
      "AZ_Prescott",
      "AZ_Show_Low",
      "AZ_Sierra_Vista",
      "AZ_St_Johns",
      "AZ_Stamm",
      "AZ_Stammn",
      "AZ_Tucson",
      "AZ_Winslow",
      "AZ_Yuma",
      "CA_Alameda",
      "CA_Apple_Valley",
      "CA_Arcata",
      "CA_Bakersfield",
      "CA_Bishop",
      "CA_Blythe",
      "CA_Burbank",
      "CA_Calexico",
      "CA_Chews",
      "CA_Chico",
      "CA_Chino",
      "CA_Churchill_Falls",
      "CA_Coalinga",
      "CA_Concord",
      "CA_Crescent_City",
      "CA_Daggett",
      "CA_Edwards",
      "CA_El_Centro",
      "CA_El_Toro",
      "CA_Fairfield",
      "CA_Fresno",
      "CA_Hawthorne",
      "CA_Hayward",
      "CA_Hemet",
      "CA_Herlong",
      "CA_Iles_De_Madeleine",
      "CA_La_Verne",
      "CA_Lake_Tahoe",
      "CA_Lancaster",
      "CA_Lemoore",
      "CA_Lompoc",
      "CA_Long_Beach",
      "CA_Los_Angeles",
      "CA_Madera",
      "CA_Mammoth_Lakes",
      "CA_Marysville",
      "CA_Merced",
      "CA_Modesto",
      "CA_Mojave",
      "CA_Montague",
      "CA_Mountain_View",
      "CA_Napa",
      "CA_Needles",
      "CA_Oakland",
      "CA_Ontario",
      "CA_Orange_County",
      "CA_Oroville",
      "CA_Oxnard",
      "CA_Palm_Springs",
      "CA_Palmdale",
      "CA_Paso_Robles",
      "CA_Port_Hueneme",
      "CA_Porterville",
      "CA_Red_Bluff",
      "CA_Redding",
      "CA_Riverside",
      "CA_Sacramento",
      "CA_Salinas",
      "CA_San_Bernardino",
      "CA_San_Clemente_Isl",
      "CA_San_Diego",
      "CA_San_Francisco",
      "CA_San_Jose",
      "CA_San_Luis_Obispo",
      "CA_San_Rafael",
      "CA_Santa_Barbara",
      "CA_Santa_Maria",
      "CA_Santa_Monica",
      "CA_Santa_Rosa",
      "CA_Stockton",
      "CA_Thermal",
      "CA_Torrance",
      "CA_Ukiah",
      "CA_Victorville",
      "CA_Visalia",
      "CA_Watsonville",
      "CA_Willows",
      "CO__Alamosa",
      "CO__Aspen",
      "CO__Broomfield",
      "CO__Cortez",
      "CO__Durango",
      "CO__Eagle",
      "CO__Fort_Collins",
      "CO__Grand_Junction",
      "CO__Greeley",
      "CO__Gunnison",
      "CO__Hayden",
      "CO__Lamar",
      "CO__Leadville",
      "CO__Montrose",
      "CO__Pueblo",
      "CO__Rifle",
      "CO__Sterling",
      "CO__Trinidad",
      "CO_Boulder",
      "CO_Colorado_Springs",
      "CO_Denver",
      "CT_Hartford",
      "CT_New_Haven",
      "CT_New_London",
      "DE_Dover",
      "DE_Georgetown",
      "DE_Wilmington",
      "FL_Boca_Raton",
      "FL_Cape_Canaveral",
      "FL_Cocoa",
      "FL_Crestview",
      "FL_Cross_City",
      "FL_Daytona_Beach",
      "FL_Fort_Lauderdale",
      "FL_Fort_Myers",
      "FL_Fort_Pierce",
      "FL_Gainesville",
      "FL_Homestead",
      "FL_Immokalee",
      "FL_Jacksonville",
      "FL_Key_West",
      "FL_Marathon",
      "FL_Melbourne",
      "FL_Miami",
      "FL_Naples",
      "FL_Ocala",
      "FL_Orlando",
      "FL_Panama_City",
      "FL_Pensacola",
      "FL_Sanford",
      "FL_Sarasota",
      "FL_St_Petersburg",
      "FL_Stuart",
      "FL_Tallahassee",
      "FL_Tampa",
      "FL_Valparaiso",
      "FL_Vero_Beach",
      "FL_West_Palm_Beach",
      "GA_Albany",
      "GA_Athens",
      "GA_Atlanta",
      "GA_Augusta",
      "GA_Brunswick",
      "GA_Columbus",
      "GA_Dalton",
      "GA_Macon",
      "GA_Marietta",
      "GA_Moultrie",
      "GA_Savannah",
      "GA_Statesboro",
      "GA_Thomasville",
      "GA_Valdosta",
      "GA_Vidalia",
      "HI_Hilo",
      "HI_Honolulu",
      "HI_Kahului",
      "HI_Kona",
      "IA_Burlington",
      "IA_Cedar_Rapids",
      "IA_Clinton",
      "IA_Davenport",
      "IA_Des_Moines",
      "IA_Dubuque",
      "IA_Fort_Dodge",
      "IA_Iowa_City",
      "IA_Mason_City",
      "IA_Ottumwa",
      "IA_Sioux_City",
      "IA_Spencer",
      "IA_Waterloo",
      "ID_Boise",
      "ID_Coeur_D_alene",
      "ID_Idaho_Falls",
      "ID_Lewiston",
      "ID_Mountain_Home",
      "ID_Pocatello",
      "ID_Salmon",
      "ID_Twin_Falls",
      "IL_Bloomington",
      "IL_Carbondale",
      "IL_Champaign",
      "IL_Chicago",
      "IL_Danville",
      "IL_Decatur",
      "IL_Galesburg",
      "IL_Glenview",
      "IL_Kankakee",
      "IL_Lawrenceville",
      "IL_Marion",
      "IL_Mattoon",
      "IL_Moline",
      "IL_Mt_Vernon",
      "IL_Peoria",
      "IL_Quincy",
      "IL_Rockford",
      "IL_Springfield",
      "IL_Sterling",
      "IL_Waukegan",
      "IN_Anderson",
      "IN_Bloomington",
      "IN_Evansville",
      "IN_Fort_Wayne",
      "IN_Gary",
      "IN_Indianapolis",
      "IN_Kokomo",
      "IN_Lafayette",
      "IN_Marion",
      "IN_Muncie",
      "IN_Peru",
      "IN_South_Bend",
      "IN_Terre_Haute",
      "IN_Valparaiso",
      "KS_Colby",
      "KS_Dodge_City",
      "KS_Emporia",
      "KS_Ft_Leavenworth",
      "KS_Ft_Scott",
      "KS_Goodland",
      "KS_Great_Bend",
      "KS_Hays",
      "KS_Hutchinson",
      "KS_Independence",
      "KS_Liberal",
      "KS_Newton",
      "KS_Pittsburg",
      "KS_Salina",
      "KS_Topeka",
      "KS_Wichita",
      "KY_Bowling_Green",
      "KY_Fort_Knox",
      "KY_Frankfort",
      "KY_Hopkinsville",
      "KY_Lexington",
      "KY_London",
      "KY_Louisville",
      "KY_Murray",
      "KY_Owensboro",
      "KY_Paducah",
      "KY_Somerset",
      "LA_Alexandria",
      "LA_Baton_Rouge",
      "LA_New_Iberia",
      "LA_New_Orleans",
      "LA_Shreveport",
      "MA_Bedford",
      "MA_Beverly",
      "MA_Boston",
      "MA_Chicopee_Falls",
      "MA_Falmouth",
      "MA_Hyannis",
      "MA_Lawrence",
      "MA_Martha_s_Vineyard",
      "MA_New_Bedford",
      "MA_Pittsfield",
      "MA_South_Weymouth",
      "MA_Westfield",
      "MA_Worcester",
      "MD_Annapolis",
      "MD_Baltimore",
      "MD_Camp_Springs",
      "MD_Cumberland",
      "MD_Hagerstown",
      "MD_Patuxent_River",
      "MD_Salisbury",
      "MD_Washington",
      "ME_Augusta",
      "ME_Bangor",
      "ME_Bar_Harbor",
      "ME_Brunswick",
      "ME_Houlton",
      "ME_Lewiston",
      "ME_Limestone",
      "ME_Millenocket",
      "ME_Portland",
      "ME_Presque_Isle",
      "ME_Rockland",
      "ME_Sanford",
      "ME_Waterville",
      "MI__St_Joseph",
      "MI_Alma",
      "MI_Alpena",
      "MI_Battle_Creek",
      "MI_Benton_Harbor",
      "MI_Cadillac",
      "MI_Detroit",
      "MI_Escanaba",
      "MI_Flint",
      "MI_Gaylord",
      "MI_Gladwin",
      "MI_Grand_Rapids",
      "MI_Hancock",
      "MI_Iron_Mountain",
      "MI_Ironwood",
      "MI_Lansing",
      "MI_Ludington",
      "MI_Manistee",
      "MI_Marquette",
      "MI_Menominee",
      "MI_Mt_Clemens",
      "MI_Muskegon",
      "MI_Oscoda",
      "MI_Pellston",
      "MI_Pontiac",
      "MI_Port_Huron",
      "MI_Reed_City",
      "MI_Saginaw",
      "MI_Sault_Ste_Marie",
      "MI_Traverse_City",
      "MN_Alexandria",
      "MN_Baudette",
      "MN_Bemidji",
      "MN_Brainerd",
      "MN_Detroit_Lakes",
      "MN_Duluth",
      "MN_Eveleth",
      "MN_Fairmont",
      "MN_Grand_Rapids",
      "MN_Hibbing",
      "MN_Internat_l_Falls",
      "MN_Mankato",
      "MN_Marshall",
      "MN_Minneapolis",
      "MN_Owatonna",
      "MN_Rochester",
      "MN_Saint_Paul",
      "MN_St_Cloud",
      "MN_Thief_River_Falls",
      "MN_Willmar",
      "MN_Worthington",
      "MO_Cape_Girardeau",
      "MO_Columbia",
      "MO_Fort_Leonard_Wood",
      "MO_Grandview",
      "MO_Jefferson_City",
      "MO_Joplin",
      "MO_Kansas_City",
      "MO_Kirksville",
      "MO_Lake_Of_Ozarks",
      "MO_Malden",
      "MO_Moberly",
      "MO_Nevada",
      "MO_Sedalia",
      "MO_Springfield",
      "MO_St_Joseph",
      "MO_St_Louis",
      "MO_Vichy",
      "MO_Warrensburg",
      "MS_Biloxi",
      "MS_Columbus",
      "MS_Greenville",
      "MS_Gulfport",
      "MS_Hattiesburg",
      "MS_Jackson",
      "MS_Laurel",
      "MS_Mccomb",
      "MS_Meridian",
      "MS_Natchez",
      "MS_Pascagoula",
      "MS_Tupelo",
      "MS_University",
      "MS_Vicksburg",
      "MT_Billings",
      "MT_Bozeman",
      "MT_Butte",
      "MT_Cut_Bank",
      "MT_Glasgow",
      "MT_Glendive",
      "MT_Great_Falls",
      "MT_Havre",
      "MT_Helena",
      "MT_Kalispell",
      "MT_Miles_City",
      "MT_Missoula",
      "MT_Sidney",
      "MT_West_Yellowstone",
      "MT_Wolf_Point",
      "NC_Asheville",
      "NC_Charlotte",
      "NC_Cherry_Point",
      "NC_Elizabeth",
      "NC_Fayetteville",
      "NC_Goldsboro",
      "NC_Greensboro",
      "NC_Greenville",
      "NC_Hickory",
      "NC_Jacksonville",
      "NC_Kinston",
      "NC_Lumberton",
      "NC_New_Bern",
      "NC_Pinehurst",
      "NC_Raleigh",
      "NC_Rocky_Mount",
      "NC_Washington",
      "NC_Wilmington",
      "NC_Winston_salem",
      "ND_Bismarck",
      "ND_Dickinson",
      "ND_Fargo",
      "ND_Grand_Forks",
      "ND_Jamestown",
      "ND_Minot",
      "ND_Williston",
      "NE_Alliance",
      "NE_Beatrice",
      "NE_Chadron",
      "NE_Columbus",
      "NE_Grand_Island",
      "NE_Hastings",
      "NE_Kearney",
      "NE_Lincoln",
      "NE_Mccook",
      "NE_Norfolk",
      "NE_North_Platte",
      "NE_Ogallala",
      "NE_Omaha",
      "NE_Oneill",
      "NE_Scottsbluff",
      "NE_Sidney",
      "NE_Valentine",
      "NH_Berlin",
      "NH_Concord",
      "NH_Keene",
      "NH_Lebanon",
      "NH_Manchester",
      "NH_Nashua",
      "NH_Portsmouth",
      "NJ_Atlantic_City",
      "NJ_Belmar",
      "NJ_Caldwell",
      "NJ_Cape_May",
      "NJ_Fort_Dix",
      "NJ_Lakehurst",
      "NJ_Millville",
      "NJ_Morristown",
      "NJ_Newark",
      "NJ_Teterboro",
      "NJ_Trenton",
      "NM_Alamogordo",
      "NM_Albuquerque",
      "NM_Artesia",
      "NM_Carlsbad",
      "NM_Clovis",
      "NM_Farmington",
      "NM_Gallup",
      "NM_Hobbs",
      "NM_Las_Cruces",
      "NM_Las_Vegas",
      "NM_Raton",
      "NM_Roswell",
      "NM_Ruidoso",
      "NM_Santa_Fe",
      "NM_Silver_City",
      "NM_Socorro",
      "NM_Truth_Or_Conseq",
      "NM_Tucumcari",
      "NV_Carson_City",
      "NV_Elko",
      "NV_Ely",
      "NV_Fallon",
      "NV_Hawthorne",
      "NV_Las_Vegas",
      "NV_Lovelock",
      "NV_Mercury",
      "NV_Reno",
      "NV_Tonopah",
      "NV_Wells",
      "NV_Winnemucca",
      "NY_Albany",
      "NY_Binghamton",
      "NY_Buffalo",
      "NY_Elmira",
      "NY_Farmingdale",
      "NY_Glens_Falls",
      "NY_Islip",
      "NY_Ithaca",
      "NY_Jamestown",
      "NY_Massena",
      "NY_Monticello",
      "NY_Newburgh",
      "NY_Niagara_Falls",
      "NY_Ogdensburg",
      "NY_Olean",
      "NY_Plattsburgh",
      "NY_Poughkeepsie",
      "NY_Rochester",
      "NY_Saranac_Lake",
      "NY_Schenectady",
      "NY_Syracuse",
      "NY_Utica",
      "NY_Watertown",
      "NY_Westchester_Cty",
      "NY_Westhampton",
      "OH_Akron",
      "OH_Cincinnati",
      "OH_Cleveland",
      "OH_Columbus",
      "OH_Dayton",
      "OH_Findlay",
      "OH_Hamilton",
      "OH_Lima",
      "OH_Mansfield",
      "OH_Middletown",
      "OH_Springfield",
      "OH_Toledo",
      "OH_Wapakoneta",
      "OH_Wilmington",
      "OH_Wooster",
      "OH_Youngstown",
      "OH_Zanesville",
      "OK_Altus",
      "OK_Ardmore",
      "OK_Bartlesville",
      "OK_Chickasha",
      "OK_Clinton",
      "OK_Duncan",
      "OK_Enid",
      "OK_Lawton",
      "OK_Mcalester",
      "OK_Miami",
      "OK_Muskogee",
      "OK_Norman",
      "OK_Oklahoma_City",
      "OK_Ponca_City",
      "OK_Stillwater",
      "OK_Tulsa",
      "OK_Woodward",
      "OR_Astoria",
      "OR_Baker",
      "OR_Bend",
      "OR_Burns",
      "OR_Corvallis",
      "OR_Eugene",
      "OR_Hillsboro",
      "OR_La_Grande",
      "OR_Medford",
      "OR_Newport",
      "OR_North_Bend",
      "OR_Ontario",
      "OR_Pendleton",
      "OR_Portland",
      "OR_Roseburg",
      "OR_Salem",
      "OR_The_Dalles",
      "OR_Troutdale",
      "PA_Altoona",
      "PA_Bradford",
      "PA_Clearfield",
      "PA_Du_Bois",
      "PA_Erie",
      "PA_Franklin",
      "PA_Harrisburg",
      "PA_Hazleton",
      "PA_Johnstown",
      "PA_Lancaster",
      "PA_Latrobe",
      "PA_Middletown",
      "PA_Philadelphia",
      "PA_Pittsburgh",
      "PA_Reading",
      "PA_Scranton",
      "PA_Williamsport",
      "PA_Willow_Grove",
      "RI_Providence",
      "RI_Westerly",
      "SC_Aiken",
      "SC_Anderson",
      "SC_Charleston",
      "SC_Columbia",
      "SC_Florence",
      "SC_Georgetown",
      "SC_Greenville",
      "SC_Greenwood",
      "SC_Myrtle_Beach",
      "SC_Orangeburg",
      "SC_Spartanburg",
      "SC_Sumter",
      "SD_Aberdeen",
      "SD_Brookings",
      "SD_Huron",
      "SD_Pierre",
      "SD_Rapid_City",
      "SD_Sioux_Falls",
      "SD_Spearfish",
      "SD_Watertown",
      "TN_Bristol",
      "TN_Chattanooga",
      "TN_Clarksville",
      "TN_Crossville",
      "TN_Greenville",
      "TN_Jackson",
      "TN_Knoxville",
      "TN_Memphis",
      "TN_Nashville",
      "TN_Paris",
      "TN_Smyrna",
      "TN_Tullahoma",
      "TX_Abilene",
      "TX_Amarillo",
      "TX_Beaumont",
      "TX_Borger",
      "TX_Brownsville",
      "TX_Brownwood",
      "TX_College_Station",
      "TX_Corpus_Christi",
      "TX_Dallas",
      "TX_Dallas",
      "TX_Del_Rio",
      "TX_El_Paso",
      "TX_Fort_Worth",
      "TX_Galveston",
      "TX_Greenville",
      "TX_Harlingen",
      "TX_Houston",
      "TX_Killeen",
      "TX_Laredo",
      "TX_Longview",
      "TX_Lubbock",
      "TX_Lufkin",
      "TX_Marshall",
      "TX_Meacham_Field",
      "TX_Midland",
      "TX_Mission",
      "TX_Palacios",
      "TX_Paris",
      "TX_Plainview",
      "TX_Rockport",
      "TX_San_Antonio",
      "TX_Sugar_Land",
      "TX_Temple",
      "TX_Tyler",
      "TX_Victoria",
      "TX_Waco",
      "TX_Wichita_Falls",
      "UT_Blanding",
      "UT_Brigham_City",
      "UT_Bryce_Canyon",
      "UT_Cedar_City",
      "UT_Delta",
      "UT_Dugway",
      "UT_Kanab",
      "UT_Logan",
      "UT_Milford",
      "UT_Moab",
      "UT_Ogden",
      "UT_Price",
      "UT_Provo",
      "UT_Richfield",
      "UT_Salt_Lake_City",
      "UT_St_George",
      "UT_Vernal",
      "UT_Wendover",
      "VA_Blacksburg",
      "VA_Charlottesville",
      "VA_Chincoteague",
      "VA_Danville",
      "VA_Dublin",
      "VA_Hampton",
      "VA_Hot_Springs",
      "VA_Lynchburg",
      "VA_Melfa",
      "VA_Newport_News",
      "VA_Norfolk",
      "VA_Oceana",
      "VA_Richmond",
      "VA_Roanoke",
      "VA_Staunton",
      "VA_Wise",
      "VT_Burlington",
      "VT_Montpelier",
      "VT_Rutland",
      "VT_Springfield",
      "WA_Bellingham",
      "WA_Bremerton",
      "WA_Chehalis",
      "WA_Ellensburg",
      "WA_Everett",
      "WA_Moses_Lake",
      "WA_Olympia",
      "WA_Port_Angeles",
      "WA_Renton",
      "WA_Seattle",
      "WA_Shelton",
      "WA_Spokane",
      "WA_Tacoma",
      "WA_Walla_Walla",
      "WA_Wenatchee",
      "WA_Whidbey_Island",
      "WA_Yakima",
      "WI_Appleton",
      "WI_Ashland",
      "WI_Camp_Douglas",
      "WI_Eau_Claire",
      "WI_Fond_Du_Lac",
      "WI_Green_Bay",
      "WI_Janesvlle",
      "WI_Kenosha",
      "WI_La_Crosse",
      "WI_Madison",
      "WI_Manitowoc",
      "WI_Marshfield",
      "WI_Milwaukee",
      "WI_Minocqua",
      "WI_Oshkosh",
      "WI_Racine",
      "WI_Rhinelander",
      "WI_Sheboygan",
      "WI_Stevens_Point",
      "WI_Sturgeon_Bay",
      "WI_Waukesha",
      "WI_Wausau",
      "WI_Wisconsin_Rapids",
      "WV_Beckley",
      "WV_Charleston",
      "WV_Clarksburg",
      "WV_Elkins",
      "WV_Greenbrier",
      "WV_Huntington",
      "WV_Martinsburg",
      "WV_Morgantown",
      "WV_Parkersburg",
      "WV_Princeton",
      "WV_Wheeling",
      "WY_Buffalo",
      "WY_Casper",
      "WY_Cheyenne",
      "WY_Cody",
      "WY_Evanston",
      "WY_Fort_Bridger",
      "WY_Gillette",
      "WY_Greybull",
      "WY_Jackson",
      "WY_Kemmerer",
      "WY_Lander",
      "WY_Laramie",
      "WY_Powell",
      "WY_Rawlins",
      "WY_Riverton",
      "WY_Rock_Springs",
      "WY_Saratoga",
      "WY_Sheridan",
      "WY_Worland",
    ],
    AK_Adak_Island: {},
    AK_Anchorage: {},
    AK_Annette_Island: {},
    AK_Barrow: {},
    AK_Bethel: {},
    AK_Big_Delta: {},
    AK_Brooks_Lake: {},
    AK_Cape_Sarichef: {},
    AK_Cordova: {},
    AK_Dillingham: {},
    AK_Dolomi: {},
    AK_Fairbanks: {},
    AK_Galena: {},
    AK_Homer: {},
    AK_Juneau: {},
    AK_Kenai: {},
    AK_Ketchikan: {},
    AK_King_Salmon: {},
    AK_Kodiak: {},
    AK_Kotzebue: {},
    AK_Mcgrath: {},
    AK_Nome: {},
    AK_Northway: {},
    AK_Prudhoe_Bay: {},
    AK_Shemya: {},
    AK_Sitka: {},
    AK_Valdez: {},
    AK_Yakutat: {},
    AL_Anniston: {},
    AL_Dothan: {},
    AL_Gadsden: {},
    AL_Hamilton: {},
    AL_Huntsville: {},
    AL_Mobile: {},
    AL_Montgomery: {},
    AL_Muscle_Shoals: {},
    AL_Selma: {},
    AL_Talladega: {},
    AL_Tuscaloosa: {},
    AR_Batesville: {},
    AR_Blytheville: {},
    AR_Buenos_Aires: {},
    AR_Camden: {},
    AR_Fort_Smith: {},
    AR_Harrison: {},
    AR_Hot_Springs: {},
    AR_Jacksonville: {},
    AR_Jonesboro: {},
    AR_Little_Rock: {},
    AR_Morrilton: {},
    AR_Pine_Bluff: {},
    AR_Resistencia: {},
    AR_Rio_Cuarto: {},
    AR_Rio_Grande: {},
    AR_San_Carlos_Debar: {},
    AR_Texarkana: {},
    AR_Walnut_Ridge: {},
    AZ_Casa_Grande: {},
    AZ_Cottonwood: {},
    AZ_Douglas: {},
    AZ_Flagstaff: {},
    AZ_Goodyear: {},
    AZ_Grand_Canyon: {},
    AZ_Kingman: {},
    AZ_Lake_Havasu_City: {},
    AZ_Marana: {},
    AZ_Nogales: {},
    AZ_Page: {},
    AZ_Phoenix: {},
    AZ_Prescott: {},
    AZ_Show_Low: {},
    AZ_Sierra_Vista: {},
    AZ_St_Johns: {},
    AZ_Stamm: {},
    AZ_Stammn: {},
    AZ_Tucson: {},
    AZ_Winslow: {},
    AZ_Yuma: {},
    CA_Alameda: {},
    CA_Apple_Valley: {},
    CA_Arcata: {},
    CA_Bakersfield: {},
    CA_Bishop: {},
    CA_Blythe: {},
    CA_Burbank: {},
    CA_Calexico: {},
    CA_Chews: {},
    CA_Chico: {},
    CA_Chino: {},
    CA_Churchill_Falls: {},
    CA_Coalinga: {},
    CA_Concord: {},
    CA_Crescent_City: {},
    CA_Daggett: {},
    CA_Edwards: {},
    CA_El_Centro: {},
    CA_El_Toro: {},
    CA_Fairfield: {},
    CA_Fresno: {},
    CA_Hawthorne: {},
    CA_Hayward: {},
    CA_Hemet: {},
    CA_Herlong: {},
    CA_Iles_De_Madeleine: {},
    CA_La_Verne: {},
    CA_Lake_Tahoe: {},
    CA_Lancaster: {},
    CA_Lemoore: {},
    CA_Lompoc: {},
    CA_Long_Beach: {},
    CA_Los_Angeles: {},
    CA_Madera: {},
    CA_Mammoth_Lakes: {},
    CA_Marysville: {},
    CA_Merced: {},
    CA_Modesto: {},
    CA_Mojave: {},
    CA_Montague: {},
    CA_Mountain_View: {},
    CA_Napa: {},
    CA_Needles: {},
    CA_Oakland: {},
    CA_Ontario: {},
    CA_Orange_County: {},
    CA_Oroville: {},
    CA_Oxnard: {},
    CA_Palm_Springs: {},
    CA_Palmdale: {},
    CA_Paso_Robles: {},
    CA_Port_Hueneme: {},
    CA_Porterville: {},
    CA_Red_Bluff: {},
    CA_Redding: {},
    CA_Riverside: {},
    CA_Sacramento: {},
    CA_Salinas: {},
    CA_San_Bernardino: {},
    CA_San_Clemente_Isl: {},
    CA_San_Diego: {},
    CA_San_Francisco: {},
    CA_San_Jose: {},
    CA_San_Luis_Obispo: {},
    CA_San_Rafael: {},
    CA_Santa_Barbara: {},
    CA_Santa_Maria: {},
    CA_Santa_Monica: {},
    CA_Santa_Rosa: {},
    CA_Stockton: {},
    CA_Thermal: {},
    CA_Torrance: {},
    CA_Ukiah: {},
    CA_Victorville: {},
    CA_Visalia: {},
    CA_Watsonville: {},
    CA_Willows: {},
    CO__Alamosa: {},
    CO__Aspen: {},
    CO__Broomfield: {},
    CO__Cortez: {},
    CO__Durango: {},
    CO__Eagle: {},
    CO__Fort_Collins: {},
    CO__Grand_Junction: {},
    CO__Greeley: {},
    CO__Gunnison: {},
    CO__Hayden: {},
    CO__Lamar: {},
    CO__Leadville: {},
    CO__Montrose: {},
    CO__Pueblo: {},
    CO__Rifle: {},
    CO__Sterling: {},
    CO__Trinidad: {},
    CO_Boulder: {},
    CO_Colorado_Springs: {},
    CO_Denver: {},
    CT_Hartford: {},
    CT_New_Haven: {},
    CT_New_London: {},
    DE_Dover: {},
    DE_Georgetown: {},
    DE_Wilmington: {},
    FL_Boca_Raton: {},
    FL_Cape_Canaveral: {},
    FL_Cocoa: {},
    FL_Crestview: {},
    FL_Cross_City: {},
    FL_Daytona_Beach: {},
    FL_Fort_Lauderdale: {},
    FL_Fort_Myers: {},
    FL_Fort_Pierce: {},
    FL_Gainesville: {},
    FL_Homestead: {},
    FL_Immokalee: {},
    FL_Jacksonville: {},
    FL_Key_West: {},
    FL_Marathon: {},
    FL_Melbourne: {},
    FL_Miami: {},
    FL_Naples: {},
    FL_Ocala: {},
    FL_Orlando: {},
    FL_Panama_City: {},
    FL_Pensacola: {},
    FL_Sanford: {},
    FL_Sarasota: {},
    FL_St_Petersburg: {},
    FL_Stuart: {},
    FL_Tallahassee: {},
    FL_Tampa: {},
    FL_Valparaiso: {},
    FL_Vero_Beach: {},
    FL_West_Palm_Beach: {},
    GA_Albany: {},
    GA_Athens: {},
    GA_Atlanta: {},
    GA_Augusta: {},
    GA_Brunswick: {},
    GA_Columbus: {},
    GA_Dalton: {},
    GA_Macon: {},
    GA_Marietta: {},
    GA_Moultrie: {},
    GA_Savannah: {},
    GA_Statesboro: {},
    GA_Thomasville: {},
    GA_Valdosta: {},
    GA_Vidalia: {},
    HI_Hilo: {},
    HI_Honolulu: {},
    HI_Kahului: {},
    HI_Kona: {},
    IA_Burlington: {},
    IA_Cedar_Rapids: {},
    IA_Clinton: {},
    IA_Davenport: {},
    IA_Des_Moines: {},
    IA_Dubuque: {},
    IA_Fort_Dodge: {},
    IA_Iowa_City: {},
    IA_Mason_City: {},
    IA_Ottumwa: {},
    IA_Sioux_City: {},
    IA_Spencer: {},
    IA_Waterloo: {},
    ID_Boise: {},
    ID_Coeur_D_alene: {},
    ID_Idaho_Falls: {},
    ID_Lewiston: {},
    ID_Mountain_Home: {},
    ID_Pocatello: {},
    ID_Salmon: {},
    ID_Twin_Falls: {},
    IL_Bloomington: {},
    IL_Carbondale: {},
    IL_Champaign: {},
    IL_Chicago: {},
    IL_Danville: {},
    IL_Decatur: {},
    IL_Galesburg: {},
    IL_Glenview: {},
    IL_Kankakee: {},
    IL_Lawrenceville: {},
    IL_Marion: {},
    IL_Mattoon: {},
    IL_Moline: {},
    IL_Mt_Vernon: {},
    IL_Peoria: {},
    IL_Quincy: {},
    IL_Rockford: {},
    IL_Springfield: {},
    IL_Sterling: {},
    IL_Waukegan: {},
    IN_Anderson: {},
    IN_Bloomington: {},
    IN_Evansville: {},
    IN_Fort_Wayne: {},
    IN_Gary: {},
    IN_Indianapolis: {},
    IN_Kokomo: {},
    IN_Lafayette: {},
    IN_Marion: {},
    IN_Muncie: {},
    IN_Peru: {},
    IN_South_Bend: {},
    IN_Terre_Haute: {},
    IN_Valparaiso: {},
    KS_Colby: {},
    KS_Dodge_City: {},
    KS_Emporia: {},
    KS_Ft_Leavenworth: {},
    KS_Ft_Scott: {},
    KS_Goodland: {},
    KS_Great_Bend: {},
    KS_Hays: {},
    KS_Hutchinson: {},
    KS_Independence: {},
    KS_Liberal: {},
    KS_Newton: {},
    KS_Pittsburg: {},
    KS_Salina: {},
    KS_Topeka: {},
    KS_Wichita: {},
    KY_Bowling_Green: {},
    KY_Fort_Knox: {},
    KY_Frankfort: {},
    KY_Hopkinsville: {},
    KY_Lexington: {},
    KY_London: {},
    KY_Louisville: {},
    KY_Murray: {},
    KY_Owensboro: {},
    KY_Paducah: {},
    KY_Somerset: {},
    LA_Alexandria: {},
    LA_Baton_Rouge: {},
    LA_New_Iberia: {},
    LA_New_Orleans: {},
    LA_Shreveport: {},
    MA_Bedford: {},
    MA_Beverly: {},
    MA_Boston: {},
    MA_Chicopee_Falls: {},
    MA_Falmouth: {},
    MA_Hyannis: {},
    MA_Lawrence: {},
    MA_Martha_s_Vineyard: {},
    MA_New_Bedford: {},
    MA_Pittsfield: {},
    MA_South_Weymouth: {},
    MA_Westfield: {},
    MA_Worcester: {},
    MD_Annapolis: {},
    MD_Baltimore: {},
    MD_Camp_Springs: {},
    MD_Cumberland: {},
    MD_Hagerstown: {},
    MD_Patuxent_River: {},
    MD_Salisbury: {},
    MD_Washington: {},
    ME_Augusta: {},
    ME_Bangor: {},
    ME_Bar_Harbor: {},
    ME_Brunswick: {},
    ME_Houlton: {},
    ME_Lewiston: {},
    ME_Limestone: {},
    ME_Millenocket: {},
    ME_Portland: {},
    ME_Presque_Isle: {},
    ME_Rockland: {},
    ME_Sanford: {},
    ME_Waterville: {},
    MI__St_Joseph: {},
    MI_Alma: {},
    MI_Alpena: {},
    MI_Battle_Creek: {},
    MI_Benton_Harbor: {},
    MI_Cadillac: {},
    MI_Detroit: {},
    MI_Escanaba: {},
    MI_Flint: {},
    MI_Gaylord: {},
    MI_Gladwin: {},
    MI_Grand_Rapids: {},
    MI_Hancock: {},
    MI_Iron_Mountain: {},
    MI_Ironwood: {},
    MI_Lansing: {},
    MI_Ludington: {},
    MI_Manistee: {},
    MI_Marquette: {},
    MI_Menominee: {},
    MI_Mt_Clemens: {},
    MI_Muskegon: {},
    MI_Oscoda: {},
    MI_Pellston: {},
    MI_Pontiac: {},
    MI_Port_Huron: {},
    MI_Reed_City: {},
    MI_Saginaw: {},
    MI_Sault_Ste_Marie: {},
    MI_Traverse_City: {},
    MN_Alexandria: {},
    MN_Baudette: {},
    MN_Bemidji: {},
    MN_Brainerd: {},
    MN_Detroit_Lakes: {},
    MN_Duluth: {},
    MN_Eveleth: {},
    MN_Fairmont: {},
    MN_Grand_Rapids: {},
    MN_Hibbing: {},
    MN_Internat_l_Falls: {},
    MN_Mankato: {},
    MN_Marshall: {},
    MN_Minneapolis: {},
    MN_Owatonna: {},
    MN_Rochester: {},
    MN_Saint_Paul: {},
    MN_St_Cloud: {},
    MN_Thief_River_Falls: {},
    MN_Willmar: {},
    MN_Worthington: {},
    MO_Cape_Girardeau: {},
    MO_Columbia: {},
    MO_Fort_Leonard_Wood: {},
    MO_Grandview: {},
    MO_Jefferson_City: {},
    MO_Joplin: {},
    MO_Kansas_City: {},
    MO_Kirksville: {},
    MO_Lake_Of_Ozarks: {},
    MO_Malden: {},
    MO_Moberly: {},
    MO_Nevada: {},
    MO_Sedalia: {},
    MO_Springfield: {},
    MO_St_Joseph: {},
    MO_St_Louis: {},
    MO_Vichy: {},
    MO_Warrensburg: {},
    MS_Biloxi: {},
    MS_Columbus: {},
    MS_Greenville: {},
    MS_Gulfport: {},
    MS_Hattiesburg: {},
    MS_Jackson: {},
    MS_Laurel: {},
    MS_Mccomb: {},
    MS_Meridian: {},
    MS_Natchez: {},
    MS_Pascagoula: {},
    MS_Tupelo: {},
    MS_University: {},
    MS_Vicksburg: {},
    MT_Billings: {},
    MT_Bozeman: {},
    MT_Butte: {},
    MT_Cut_Bank: {},
    MT_Glasgow: {},
    MT_Glendive: {},
    MT_Great_Falls: {},
    MT_Havre: {},
    MT_Helena: {},
    MT_Kalispell: {},
    MT_Miles_City: {},
    MT_Missoula: {},
    MT_Sidney: {},
    MT_West_Yellowstone: {},
    MT_Wolf_Point: {},
    NC_Asheville: {},
    NC_Charlotte: {},
    NC_Cherry_Point: {},
    NC_Elizabeth: {},
    NC_Fayetteville: {},
    NC_Goldsboro: {},
    NC_Greensboro: {},
    NC_Greenville: {},
    NC_Hickory: {},
    NC_Jacksonville: {},
    NC_Kinston: {},
    NC_Lumberton: {},
    NC_New_Bern: {},
    NC_Pinehurst: {},
    NC_Raleigh: {},
    NC_Rocky_Mount: {},
    NC_Washington: {},
    NC_Wilmington: {},
    NC_Winston_salem: {},
    ND_Bismarck: {},
    ND_Dickinson: {},
    ND_Fargo: {},
    ND_Grand_Forks: {},
    ND_Jamestown: {},
    ND_Minot: {},
    ND_Williston: {},
    NE_Alliance: {},
    NE_Beatrice: {},
    NE_Chadron: {},
    NE_Columbus: {},
    NE_Grand_Island: {},
    NE_Hastings: {},
    NE_Kearney: {},
    NE_Lincoln: {},
    NE_Mccook: {},
    NE_Norfolk: {},
    NE_North_Platte: {},
    NE_Ogallala: {},
    NE_Omaha: {},
    NE_Oneill: {},
    NE_Scottsbluff: {},
    NE_Sidney: {},
    NE_Valentine: {},
    NH_Berlin: {},
    NH_Concord: {},
    NH_Keene: {},
    NH_Lebanon: {},
    NH_Manchester: {},
    NH_Nashua: {},
    NH_Portsmouth: {},
    NJ_Atlantic_City: {},
    NJ_Belmar: {},
    NJ_Caldwell: {},
    NJ_Cape_May: {},
    NJ_Fort_Dix: {},
    NJ_Lakehurst: {},
    NJ_Millville: {},
    NJ_Morristown: {},
    NJ_Newark: {},
    NJ_Teterboro: {},
    NJ_Trenton: {},
    NM_Alamogordo: {},
    NM_Albuquerque: {},
    NM_Artesia: {},
    NM_Carlsbad: {},
    NM_Clovis: {},
    NM_Farmington: {},
    NM_Gallup: {},
    NM_Hobbs: {},
    NM_Las_Cruces: {},
    NM_Las_Vegas: {},
    NM_Raton: {},
    NM_Roswell: {},
    NM_Ruidoso: {},
    NM_Santa_Fe: {},
    NM_Silver_City: {},
    NM_Socorro: {},
    NM_Truth_Or_Conseq: {},
    NM_Tucumcari: {},
    NV_Carson_City: {},
    NV_Elko: {},
    NV_Ely: {},
    NV_Fallon: {},
    NV_Hawthorne: {},
    NV_Las_Vegas: {},
    NV_Lovelock: {},
    NV_Mercury: {},
    NV_Reno: {},
    NV_Tonopah: {},
    NV_Wells: {},
    NV_Winnemucca: {},
    NY_Albany: {},
    NY_Binghamton: {},
    NY_Buffalo: {},
    NY_Elmira: {},
    NY_Farmingdale: {},
    NY_Glens_Falls: {},
    NY_Islip: {},
    NY_Ithaca: {},
    NY_Jamestown: {},
    NY_Massena: {},
    NY_Monticello: {},
    NY_Newburgh: {},
    NY_Niagara_Falls: {},
    NY_Ogdensburg: {},
    NY_Olean: {},
    NY_Plattsburgh: {},
    NY_Poughkeepsie: {},
    NY_Rochester: {},
    NY_Saranac_Lake: {},
    NY_Schenectady: {},
    NY_Syracuse: {},
    NY_Utica: {},
    NY_Watertown: {},
    NY_Westchester_Cty: {},
    NY_Westhampton: {},
    OH_Akron: {},
    OH_Cincinnati: {},
    OH_Cleveland: {},
    OH_Columbus: {},
    OH_Dayton: {},
    OH_Findlay: {},
    OH_Hamilton: {},
    OH_Lima: {},
    OH_Mansfield: {},
    OH_Middletown: {},
    OH_Springfield: {},
    OH_Toledo: {},
    OH_Wapakoneta: {},
    OH_Wilmington: {},
    OH_Wooster: {},
    OH_Youngstown: {},
    OH_Zanesville: {},
    OK_Altus: {},
    OK_Ardmore: {},
    OK_Bartlesville: {},
    OK_Chickasha: {},
    OK_Clinton: {},
    OK_Duncan: {},
    OK_Enid: {},
    OK_Lawton: {},
    OK_Mcalester: {},
    OK_Miami: {},
    OK_Muskogee: {},
    OK_Norman: {},
    OK_Oklahoma_City: {},
    OK_Ponca_City: {},
    OK_Stillwater: {},
    OK_Tulsa: {},
    OK_Woodward: {},
    OR_Astoria: {},
    OR_Baker: {},
    OR_Bend: {},
    OR_Burns: {},
    OR_Corvallis: {},
    OR_Eugene: {},
    OR_Hillsboro: {},
    OR_La_Grande: {},
    OR_Medford: {},
    OR_Newport: {},
    OR_North_Bend: {},
    OR_Ontario: {},
    OR_Pendleton: {},
    OR_Portland: {},
    OR_Roseburg: {},
    OR_Salem: {},
    OR_The_Dalles: {},
    OR_Troutdale: {},
    PA_Altoona: {},
    PA_Bradford: {},
    PA_Clearfield: {},
    PA_Du_Bois: {},
    PA_Erie: {},
    PA_Franklin: {},
    PA_Harrisburg: {},
    PA_Hazleton: {},
    PA_Johnstown: {},
    PA_Lancaster: {},
    PA_Latrobe: {},
    PA_Middletown: {},
    PA_Philadelphia: {},
    PA_Pittsburgh: {},
    PA_Reading: {},
    PA_Scranton: {},
    PA_Williamsport: {},
    PA_Willow_Grove: {},
    RI_Providence: {},
    RI_Westerly: {},
    SC_Aiken: {},
    SC_Anderson: {},
    SC_Charleston: {},
    SC_Columbia: {},
    SC_Florence: {},
    SC_Georgetown: {},
    SC_Greenville: {},
    SC_Greenwood: {},
    SC_Myrtle_Beach: {},
    SC_Orangeburg: {},
    SC_Spartanburg: {},
    SC_Sumter: {},
    SD_Aberdeen: {},
    SD_Brookings: {},
    SD_Huron: {},
    SD_Pierre: {},
    SD_Rapid_City: {},
    SD_Sioux_Falls: {},
    SD_Spearfish: {},
    SD_Watertown: {},
    TN_Bristol: {},
    TN_Chattanooga: {},
    TN_Clarksville: {},
    TN_Crossville: {},
    TN_Greenville: {},
    TN_Jackson: {},
    TN_Knoxville: {},
    TN_Memphis: {},
    TN_Nashville: {},
    TN_Paris: {},
    TN_Smyrna: {},
    TN_Tullahoma: {},
    TX_Abilene: {},
    TX_Amarillo: {},
    TX_Beaumont: {},
    TX_Borger: {},
    TX_Brownsville: {},
    TX_Brownwood: {},
    TX_College_Station: {},
    TX_Corpus_Christi: {},
    TX_Dallas: {},
    TX_Dallas: {},
    TX_Del_Rio: {},
    TX_El_Paso: {},
    TX_Fort_Worth: {},
    TX_Galveston: {},
    TX_Greenville: {},
    TX_Harlingen: {},
    TX_Houston: {},
    TX_Killeen: {},
    TX_Laredo: {},
    TX_Longview: {},
    TX_Lubbock: {},
    TX_Lufkin: {},
    TX_Marshall: {},
    TX_Meacham_Field: {},
    TX_Midland: {},
    TX_Mission: {},
    TX_Palacios: {},
    TX_Paris: {},
    TX_Plainview: {},
    TX_Rockport: {},
    TX_San_Antonio: {},
    TX_Sugar_Land: {},
    TX_Temple: {},
    TX_Tyler: {},
    TX_Victoria: {},
    TX_Waco: {},
    TX_Wichita_Falls: {},
    UT_Blanding: {},
    UT_Brigham_City: {},
    UT_Bryce_Canyon: {},
    UT_Cedar_City: {},
    UT_Delta: {},
    UT_Dugway: {},
    UT_Kanab: {},
    UT_Logan: {},
    UT_Milford: {},
    UT_Moab: {},
    UT_Ogden: {},
    UT_Price: {},
    UT_Provo: {},
    UT_Richfield: {},
    UT_Salt_Lake_City: {},
    UT_St_George: {},
    UT_Vernal: {},
    UT_Wendover: {},
    VA_Blacksburg: {},
    VA_Charlottesville: {},
    VA_Chincoteague: {},
    VA_Danville: {},
    VA_Dublin: {},
    VA_Hampton: {},
    VA_Hot_Springs: {},
    VA_Lynchburg: {},
    VA_Melfa: {},
    VA_Newport_News: {},
    VA_Norfolk: {},
    VA_Oceana: {},
    VA_Richmond: {},
    VA_Roanoke: {},
    VA_Staunton: {},
    VA_Wise: {},
    VT_Burlington: {},
    VT_Montpelier: {},
    VT_Rutland: {},
    VT_Springfield: {},
    WA_Bellingham: {},
    WA_Bremerton: {},
    WA_Chehalis: {},
    WA_Ellensburg: {},
    WA_Everett: {},
    WA_Moses_Lake: {},
    WA_Olympia: {},
    WA_Port_Angeles: {},
    WA_Renton: {},
    WA_Seattle: {},
    WA_Shelton: {},
    WA_Spokane: {},
    WA_Tacoma: {},
    WA_Walla_Walla: {},
    WA_Wenatchee: {},
    WA_Whidbey_Island: {},
    WA_Yakima: {},
    WI_Appleton: {},
    WI_Ashland: {},
    WI_Camp_Douglas: {},
    WI_Eau_Claire: {},
    WI_Fond_Du_Lac: {},
    WI_Green_Bay: {},
    WI_Janesvlle: {},
    WI_Kenosha: {},
    WI_La_Crosse: {},
    WI_Madison: {},
    WI_Manitowoc: {},
    WI_Marshfield: {},
    WI_Milwaukee: {},
    WI_Minocqua: {},
    WI_Oshkosh: {},
    WI_Racine: {},
    WI_Rhinelander: {},
    WI_Sheboygan: {},
    WI_Stevens_Point: {},
    WI_Sturgeon_Bay: {},
    WI_Waukesha: {},
    WI_Wausau: {},
    WI_Wisconsin_Rapids: {},
    WV_Beckley: {},
    WV_Charleston: {},
    WV_Clarksburg: {},
    WV_Elkins: {},
    WV_Greenbrier: {},
    WV_Huntington: {},
    WV_Martinsburg: {},
    WV_Morgantown: {},
    WV_Parkersburg: {},
    WV_Princeton: {},
    WV_Wheeling: {},
    WY_Buffalo: {},
    WY_Casper: {},
    WY_Cheyenne: {},
    WY_Cody: {},
    WY_Evanston: {},
    WY_Fort_Bridger: {},
    WY_Gillette: {},
    WY_Greybull: {},
    WY_Jackson: {},
    WY_Kemmerer: {},
    WY_Lander: {},
    WY_Laramie: {},
    WY_Powell: {},
    WY_Rawlins: {},
    WY_Riverton: {},
    WY_Rock_Springs: {},
    WY_Saratoga: {},
    WY_Sheridan: {},
    WY_Worland: {},
  },
  UZBEKISTAN: {
    citiesNames: ["Tashkent"],
    Tashkent: {},
  },
  VENEZUELA: {
    citiesNames: [
      "Barcelona",
      "Barquisimeto",
      "Caracas",
      "Coro",
      "Las_Piedras",
      "Maracaibo",
      "Maracay",
      "Maturin",
      "Porlamar",
    ],
    Barcelona: {},
    Barquisimeto: {},
    Caracas: {},
    Coro: {},
    Las_Piedras: {},
    Maracaibo: {},
    Maracay: {},
    Maturin: {},
    Porlamar: {},
  },
  VIETNAM: {
    citiesNames: ["Hanoi", "Ho_Chi_Minh_City"],
    Hanoi: {},
    Ho_Chi_Minh_City: {},
  },
  YEMEN: {
    citiesNames: [
      "Adan",
      "Amran",
      "Bajil",
      "Bayda",
      "Bayl_Al_Faqih",
      "Dhamar",
      "Dhi_Sufal",
      "Hajjah",
      "Hodeida",
      "Ib",
      "Jaar",
      "Lahij",
      "Marawia",
      "Marib",
      "Mukalla",
      "Radaa",
      "Sahar",
      "Sana",
      "Sayyan",
      "Shahar",
      "Sumara",
      "Taiz",
      "Yarim",
      "Zabid",
    ],
    Adan: {},
    Amran: {},
    Bajil: {},
    Bayda: {},
    Bayl_Al_Faqih: {},
    Dhamar: {},
    Dhi_Sufal: {},
    Hajjah: {},
    Hodeida: {},
    Ib: {},
    Jaar: {},
    Lahij: {},
    Marawia: {},
    Marib: {},
    Mukalla: {},
    Radaa: {},
    Sahar: {},
    Sana: {},
    Sayyan: {},
    Shahar: {},
    Sumara: {},
    Taiz: {},
    Yarim: {},
    Zabid: {},
  },
  YUGOSLAVIA: {
    citiesNames: ["Belgrade", "Dubrovnik"],
    Belgrade: {},
    Dubrovnik: {},
  },
  ZAIRE: {
    citiesNames: [
      "Gemena",
      "Goma",
      "Isiro",
      "Kamina",
      "Kindu",
      "Kinshasa",
      "Kisangani",
      "Lubumbashi",
      "Mbandaka",
      "Mbuji_Mayi",
    ],
    Gemena: {},
    Goma: {},
    Isiro: {},
    Kamina: {},
    Kindu: {},
    Kinshasa: {},
    Kisangani: {},
    Lubumbashi: {},
    Mbandaka: {},
    Mbuji_Mayi: {},
  },
  ZAMBIA: {
    citiesNames: ["Livingstone", "Lusaka", "Ndola"],
    Livingstone: {},
    Lusaka: {},
    Ndola: {},
  },
  ZIMBABWE: {
    citiesNames: ["Bulawayo"],
    Bulawayo: {},
  },
};
